import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const uploadRouteSource = fs.readFileSync('app/(app)/events/page.tsx', 'utf8')
const savedRouteSource = fs.readFileSync('app/(app)/events/[id]/page.tsx', 'utf8')
const inlineHeaderSource = fs.readFileSync('components/events/inline-event-details-header.tsx', 'utf8')

test('both Event Details flows render one shared section-level editor without route-level edit state', () => {
  assert.match(uploadRouteSource, /import InlineEventDetailsHeader/)
  assert.match(savedRouteSource, /import InlineEventDetailsHeader/)
  assert.match(uploadRouteSource, /<InlineEventDetailsHeader/)
  assert.match(savedRouteSource, /<InlineEventDetailsHeader/)
  assert.doesNotMatch(uploadRouteSource, /Edit event details|eventEditing|setEventEditing|EventIdentityEditor/)
  assert.doesNotMatch(savedRouteSource, /Edit event details|eventEditing|setEventEditing|EventIdentityEditor/)
})

test('the complete labeled Event Details form is the default and only layout', () => {
  assert.match(inlineHeaderSource, /data-testid="event-details-form"/)
  assert.match(inlineHeaderSource, /const \[eventForm, setEventForm\]/)
  assert.match(inlineHeaderSource, />Event name<\/label>/)
  assert.match(inlineHeaderSource, />Event type<\/label>/)
  assert.match(inlineHeaderSource, />Event date<\/label>/)
  assert.match(inlineHeaderSource, />Venue<\/label>/)
  assert.match(inlineHeaderSource, /placeholder="Enter event name"/)
  assert.match(inlineHeaderSource, /md:grid-cols-3/)
  assert.match(inlineHeaderSource, /text-base font-medium[\s\S]*?text-\[#111827\][\s\S]*?md:text-\[30px\][\s\S]*?md:font-semibold/)
  assert.match(inlineHeaderSource, /placeholder:text-base placeholder:font-medium placeholder:text-\[#111827\]/)
  assert.match(inlineHeaderSource, /md:placeholder:text-\[26px\]/)
  assert.match(inlineHeaderSource, /h-\[52px\][\s\S]*?rounded-xl[\s\S]*?border-\[#E5E7EB\]/)
  assert.match(inlineHeaderSource, /mobileHiddenLabelClassName = 'sr-only md:not-sr-only/)
  assert.match(inlineHeaderSource, /<label htmlFor="event-details-name" className=\{mobileHiddenLabelClassName\}>/)
  assert.match(inlineHeaderSource, /<label htmlFor="event-details-type" className=\{mobileHiddenLabelClassName\}>/)
  assert.match(inlineHeaderSource, /<label htmlFor="event-details-date" className=\{mobileHiddenLabelClassName\}>/)
  assert.match(inlineHeaderSource, /<label htmlFor="event-details-venue" className=\{mobileHiddenLabelClassName\}>/)
  assert.doesNotMatch(inlineHeaderSource, /pb-1 pt-5 text-base/)
  assert.match(inlineHeaderSource, /<CalendarIcon \/>/)
  assert.match(inlineHeaderSource, /\[text-align:left\]/)
  assert.match(inlineHeaderSource, /grid-cols-2 gap-3 md:grid-cols-3/)
  assert.match(inlineHeaderSource, /col-span-2 min-w-0 md:col-span-1/)
  assert.match(inlineHeaderSource, />\s*Event Name\s*</)
  assert.match(inlineHeaderSource, />\s*Event Date\s*</)
  assert.match(inlineHeaderSource, />\s*Event Type\s*</)
  assert.match(inlineHeaderSource, /isUnnamedDefaultType\(value\)/)
  assert.match(inlineHeaderSource, /isUnnamedDefaultDate\(value\)/)
  assert.match(inlineHeaderSource, /onPointerDown=\{\(\) => setMobileTypeIsEmpty\(false\)\}/)
  assert.match(inlineHeaderSource, /onPointerDown=\{\(\) => setMobileDateIsEmpty\(false\)\}/)
  assert.match(savedRouteSource, /className="-mt-1 min-h-full[\s\S]*?pt-0 md:mt-0[\s\S]*?md:pt-4"/)
  assert.match(savedRouteSource, /className="mb-2 inline-flex[\s\S]*?md:mb-4/)
  assert.doesNotMatch(inlineHeaderSource, /mobileActions/)
  assert.doesNotMatch(savedRouteSource, /mobileActionsOpen|aria-label="Event actions"/)
  assert.match(savedRouteSource, />\s*\+ Add Vendors\s*</)
  assert.match(inlineHeaderSource, /name: value\.name\.trim\(\) === 'Untitled Event' \? '' : value\.name/)
  assert.doesNotMatch(inlineHeaderSource, /event-details-read-mode|event-details-edit-mode/)
  assert.doesNotMatch(inlineHeaderSource, /isEditingEvent|setIsEditingEvent|>\s*Edit event\s*<|>\s*Cancel\s*<|>\s*Save changes\s*</)
  assert.doesNotMatch(inlineHeaderSource, /Save event name|>✓</)
})

test('name autosaves once after 700ms of inactivity and flushes immediately on blur', () => {
  assert.match(inlineHeaderSource, /queueSave\('name', 700\)/)
  assert.match(inlineHeaderSource, /if \(nameTimerRef\.current\) window\.clearTimeout\(nameTimerRef\.current\)/)
  assert.match(inlineHeaderSource, /nameTimerRef\.current = window\.setTimeout\(\(\) => \{[\s\S]*?void flushSaves\(\)[\s\S]*?\}, delay\)/)
  assert.match(inlineHeaderSource, /onBlur=\{\(\) => \{[\s\S]*?nameTimerRef\.current = null[\s\S]*?void flushSaves\(\)/)
  assert.match(inlineHeaderSource, /fields\.has\('name'\) && nextName && nextName !== savedForm\.name/)
  assert.doesNotMatch(inlineHeaderSource, /updates\.name = ['"]Enter event name['"]/)
})

test('type date and venue autosave immediately through the shared cloud callback', () => {
  assert.match(inlineHeaderSource, /type="date"/)
  assert.match(inlineHeaderSource, /queueSave\('type'\)/)
  assert.match(inlineHeaderSource, /if \(event\.target\.value\) queueSave\('date'\)/)
  assert.match(inlineHeaderSource, /onSelect=\{\(venue\) => \{[\s\S]*?queueSave\('venueName'\)/)
  assert.match(inlineHeaderSource, /onAddNew=\{\(venueName\) => \{[\s\S]*?queueSave\('venueName'\)/)
  assert.match(uploadRouteSource, /onSave=\{savePendingEventMetadataToCloud\}/)
  assert.match(savedRouteSource, /onSave=\{saveEventMetadata\}/)
})

test('venue selection and removal persist the existing cloud-backed relationship fields', () => {
  assert.match(inlineHeaderSource, /venueName: venue\.name/)
  assert.match(inlineHeaderSource, /venueInstagram: venue\.instagram \?\? ''/)
  assert.match(inlineHeaderSource, /venueVendorId: venue\.vendorId/)
  assert.match(inlineHeaderSource, /venueName: nextVenueName[\s\S]*?venueVendorId: undefined/)
  assert.match(inlineHeaderSource, /placeholder="Select or add venue"/)
  assert.match(inlineHeaderSource, /mobilePlaceholder="Venue"/)
  assert.match(inlineHeaderSource, /<VenueAutocomplete/)
  assert.match(inlineHeaderSource, /showAddNew/)
})

test('serialized autosave preserves newer drafts and updates its saved baseline after success', () => {
  assert.match(inlineHeaderSource, /if \(requestRef\.current \|\| pendingFieldsRef\.current\.size === 0\) return/)
  assert.match(inlineHeaderSource, /const formSnapshot = \{ \.\.\.eventFormRef\.current \}/)
  assert.match(inlineHeaderSource, /if \(pendingFieldsRef\.current\.size > 0\) \{[\s\S]*?await flushSaves\(\)/)
  assert.match(inlineHeaderSource, /if \(!requestRef\.current && pendingFieldsRef\.current\.size === 0\) \{[\s\S]*?setSaveStatus\('saved'\)/)
  assert.match(inlineHeaderSource, /markFieldsSaved\(formSnapshot, fields\)/)
  assert.match(inlineHeaderSource, />Saved</)
  assert.match(inlineHeaderSource, /Saving…/)
  assert.match(inlineHeaderSource, /catch \(error\)[\s\S]*?setSaveStatus\('error'\)/)
  assert.doesNotMatch(inlineHeaderSource, /catch \(error\)[\s\S]*?setEventForm/)
  assert.doesNotMatch(inlineHeaderSource, /onChange=\{[\s\S]{0,180}onSave/)
})

test('failed autosave keeps the form value and exposes a compact Retry action', () => {
  assert.match(inlineHeaderSource, /Couldn&apos;t save/)
  assert.match(inlineHeaderSource, />\s*Retry\s*</)
  assert.match(inlineHeaderSource, /function retrySave\(\)/)
  assert.match(inlineHeaderSource, /failedFieldsRef\.current\.forEach/)
  assert.match(inlineHeaderSource, /pendingFieldsRef\.current\.add\(field\)/)
  assert.match(inlineHeaderSource, /if \(!venueName\.trim\(\)\) queueSave\('venueName'\)/)
  assert.doesNotMatch(inlineHeaderSource, /localStorage|sessionStorage/)
})

test('upload-route edits reuse the canonical UUID and preserve attached media before reload', () => {
  const saveStart = uploadRouteSource.indexOf('async function savePendingEventMetadataToCloud')
  const saveEnd = uploadRouteSource.indexOf('function handleCreateEventClick', saveStart)
  const saveSource = uploadRouteSource.slice(saveStart, saveEnd)

  assert.match(saveSource, /await ensurePendingCloudEvent/)
  assert.match(saveSource, /await loadEventFromCloud\(createdEvent\.id\)/)
  assert.match(saveSource, /id: currentCloudEvent\.id/)
  assert.match(saveSource, /media: currentCloudEvent\.media/)
  assert.match(saveSource, /cover: currentCloudEvent\.cover/)
  assert.match(saveSource, /createdAt: currentCloudEvent\.createdAt/)
  assert.match(saveSource, /await saveEventToCloud\(updatedEvent\)/)
  assert.match(saveSource, /savedEvent\.id !== currentCloudEvent\.id/)
  assert.match(saveSource, /await loadEventFromCloud\(currentCloudEvent\.id\)/)
  assert.doesNotMatch(saveSource, /createCloudEventWithMedia\(\{[\s\S]*?createCloudEventWithMedia\(\{/)
  assert.doesNotMatch(saveSource, /localStorage|sessionStorage/)
})

test('upload creation is deduplicated and navigation waits for inline persistence', () => {
  const creationStart = uploadRouteSource.indexOf('function ensurePendingCloudEvent')
  const creationEnd = uploadRouteSource.indexOf('async function savePendingEventMetadataToCloud', creationStart)
  const creationSource = uploadRouteSource.slice(creationStart, creationEnd)
  const continueStart = uploadRouteSource.indexOf('async function continueWithPendingBatch')
  const continueEnd = uploadRouteSource.indexOf('function ensurePendingCloudEvent', continueStart)
  const continueSource = uploadRouteSource.slice(continueStart, continueEnd)

  assert.match(creationSource, /if \(eventId\) return loadEventFromCloud\(eventId\)/)
  assert.match(creationSource, /if \(cloudEventPromiseRef\.current\) return cloudEventPromiseRef\.current/)
  assert.match(creationSource, /cloudCreationKeyRef\.current/)
  assert.match(creationSource, /autoSavedEventIdRef\.current = confirmedEvent\.id/)
  assert.match(continueSource, /if \(pendingInlineSaveRef\.current\) await pendingInlineSaveRef\.current/)
  assert.match(continueSource, /const reloadedEvent = await loadEventFromCloud\(confirmedEvent\.id\)/)
  assert.match(continueSource, /router\.replace\(`\/events\/\$\{reloadedEvent\.id\}`\)/)
})

test('saved-route reload uses the updated same-UUID event with its media intact', () => {
  assert.match(savedRouteSource, /loadEventFromCloud\(params\.id\)/)
  assert.match(savedRouteSource, /saveLocalEvent\(cloudEvent\)/)
  assert.match(savedRouteSource, /media: localEvent\.media/)
  assert.match(savedRouteSource, /cover: localEvent\.cover/)
  assert.match(savedRouteSource, /await loadEventFromCloud\(localEvent\.id\)/)
})
