import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
const output = await build({entryPoints:['app/api/monthly-plan/route.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'test-supabase',setup(build){build.onResolve({filter:/^@\/lib\/supabase\/server$/},()=>({path:'fake-supabase',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createClient=()=>globalThis.__MONTHLY_TEST_SB;'}));}}]});
const {GET,PUT}=await import(`data:text/javascript;base64,${Buffer.from(output.outputFiles[0].contents).toString('base64')}`);
const OWNER='11111111-1111-1111-1111-111111111111',P={id:'00000000-0000-4000-8000-000000000001',text:'Exact priority'};
function fixture(results=[],user={id:OWNER}){const calls=[];globalThis.__MONTHLY_TEST_SB={auth:{getUser:async()=>({data:{user},error:null})},from(table){const call={table,chain:[]};calls.push(call);const builder=new Proxy({}, {get(_,key){if(key==='then')return(resolve,reject)=>Promise.resolve(typeof results[0]==='function'?results.shift()(call):results.shift()||{data:null,error:null}).then(resolve,reject);return(...args)=>{call.chain.push([key,...args]);return builder;};}});return builder;}};return calls;}
const request=(body,headers={})=>new Request('https://fixture.invalid/api/monthly-plan',{method:'PUT',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const valid={month:'2026-10',revision:0,priorities:[P]};
test('no user and development mock cannot read or write',async()=>{for(const user of [null,{id:'dev'}]){const calls=fixture([],user);assert.equal((await GET(new Request('https://fixture.invalid/api/monthly-plan?month=2026-10'))).status,401);assert.equal((await PUT(request(valid))).status,401);assert.equal(calls.length,0);}});
test('rejects cross-origin writes, missing version, extra owner and malformed or oversized bodies before querying',async()=>{const calls=fixture();assert.equal((await PUT(request(valid,{Origin:'https://evil.invalid'}))).status,403);for(const bad of [{...valid,revision:undefined},{...valid,user_id:'foreign'},{...valid,priorities:[{...P,text:''}]}])assert.equal((await PUT(request(bad))).status,400);assert.equal((await PUT(request(valid,{'Content-Length':'70000'}))).status,413);assert.equal((await PUT(request({...valid,priorities:[{...P,text:'x'.repeat(70000)}]}))).status,413);assert.equal(calls.length,0);});
test('insert is create-only, scoped to auth owner, canonical revision returned',async()=>{const calls=fixture([{data:{revision:1,priorities:[P]},error:null}]);const result=await PUT(request(valid));assert.equal(result.status,200);assert.deepEqual(await result.json(),{month:'2026-10',revision:1,priorities:[P]});assert.equal(calls[0].table,'monthly_feature_plans');assert.deepEqual(calls[0].chain[0],['insert',{user_id:OWNER,month:'2026-10-01',priorities:[P],revision:1}]);});
test('all edits filter owner, month AND exact revision; stale updates and insert races conflict',async()=>{const calls=fixture([{data:null,error:null},{data:null,error:{code:'23505'}}]);assert.equal((await PUT(request({...valid,revision:4}))).status,409);assert.equal((await PUT(request(valid))).status,409);assert.ok(calls[0].chain.some(c=>c[0]==='eq'&&c[1]==='user_id'&&c[2]===OWNER));assert.ok(calls[0].chain.some(c=>c[0]==='eq'&&c[1]==='month'&&c[2]==='2026-10-01'));assert.ok(calls[0].chain.some(c=>c[0]==='eq'&&c[1]==='revision'&&c[2]===4));assert.equal(calls.some(c=>c.chain.some(a=>a[0]==='upsert')),false);});
test('missing migration returns unavailable and never falls back to local or review-queue writes',async()=>{const calls=fixture([{data:null,error:{code:'42P01',message:'private detail'}}]);const response=await PUT(request(valid));assert.equal(response.status,503);assert.equal(JSON.stringify(await response.json()).includes('private detail'),false);assert.deepEqual(calls.map(c=>c.table),['monthly_feature_plans']);});
test('month reads are owner scoped, bounded, preserve canonical dates and use real statuses',async()=>{const calls=fixture([{data:{revision:2,priorities:[P]},error:null},{data:[{slot_id:'d',planning_date:'2026-10-09',state:'draft',draft_id:'draft-1'},{slot_id:'a',planning_date:'2026-10-16',state:'approved',approved_post_id:'post-1'}],error:null},{data:{slots:[{draftId:'draft-1',purpose:'Autumn menu',revision:{status:'waiting'}}]},error:null},{data:[{id:'post-1',title:'Booked party',status:'scheduled'}],error:null}]);const response=await GET(new Request('https://fixture.invalid/api/monthly-plan?month=2026-10'));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');const data=await response.json();assert.deepEqual(data.entries.map(e=>[e.date,e.title,e.status]),[['2026-10-09','Autumn menu','Waiting'],['2026-10-16','Booked party','Scheduled']]);for(const call of calls)assert.ok(call.chain.some(c=>c[0]==='eq'&&c[1]==='user_id'&&c[2]===OWNER),call.table);assert.ok(calls[1].chain.some(c=>c[0]==='limit'&&c[1]===201));assert.ok(calls[1].chain.some(c=>c[0]==='gte'&&c[1]==='planning_date'&&c[2]==='2026-10-01'));assert.ok(calls[1].chain.some(c=>c[0]==='lt'&&c[1]==='planning_date'&&c[2]==='2026-11-01'));});
test('GET read errors are never represented as a successfully empty plan',async()=>{fixture([{error:{code:'missing'},data:null},{data:[],error:null},{data:null,error:null}]);assert.equal((await GET(new Request('https://fixture.invalid/api/monthly-plan?month=2026-10'))).status,503);});
