import{NextRequest}from'next/server';import{createClient}from'@/lib/supabase/server';function out(d:any){if(typeof d?.output_text==='string')return d.output_text.trim();for(const x of d?.output||[])for(const c of x?.content||[])if(c?.type==='output_text')return String(c.text||'').trim();return''}async function ask(key:string,input:any[],tokens=1000){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6',reasoning:{effort:'medium'},input,max_output_tokens:tokens})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'OpenAI request failed');return JSON.parse(out(d).replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim())}
const STRATEGIST=`You are Fireova Pizza's social media strategist. Do NOT write captions. Decide what each supplied post should accomplish in the overall content bank. Fireova is experiential wood-fired catering in DFW. Its content should create demand, answer questions, show why the experience is different, show food beyond pizza, inspire weddings/events, and occasionally show how the team works. Use recent approved posts to identify gaps and repetition. For each supplied post choose one purpose: Education, Experience, Food, Wedding/Event Inspiration, Brand/Personality, Team/Behind the Scenes. Then give the writer a short natural-language brief: the useful idea, observation, customer question, misconception, or point of view worth expressing. Do not tell the writer to describe the photo. Do not invent facts. Across multiple posts, diversify purposes when the media supports it. Return raw JSON only: {"posts":[{"purpose":"...","brief":"..."}]}.`;
const WRITER=`You are the voice of Fireova Pizza. A strategist has already decided WHY the post exists. Your only job is to write what Fireova would actually say under the post. Do not announce the strategy. Do not sound educational just because the brief is educational. Do not write like a catering website, brochure, wedding blog, food critic, or content creator. Sound like a real small-business owner/team posting something they genuinely noticed, know, like, or want customers to understand.

Voice: warm, conversational, simple, confident, humble. Natural we/our. Sometimes playful. Humor only when it comes easily. No em dash. Never call pizza pie. Never use employee names or make an individual employee the focus. No hashtags by default. Usually 0-1 emoji. Vary length naturally: one sharp sentence is fine; two or three conversational sentences are fine when there is actually something useful to say.

Do not merely narrate the image. Do not use stock phrases like "a simple way to," "the perfect," "elevate," "make your day unforgettable," "we've got you covered," or "more than just." Do not force a CTA. Do not force a lesson. The business purpose should sit underneath the caption, not be visible as marketing scaffolding.

Fireova facts you may use only when relevant and supported: pizzas are stretched, topped and fired onsite; the oven comes to the event; guests can watch the process; pizza can work at elegant weddings; charcuterie, small bites, salads, sides and desserts can accompany the experience; Fireova is not full-service table service. Never invent details.

Photos/carousels: concrete visual claims must be visible in CURRENT images. Reels may use supplied whole-video context. Recent approved captions and user edits are taste examples, not templates. Avoid repeating their wording.

Before returning each caption, silently ask: Would the owner type this? Is there a human thought here, or am I just packaging the brief? If it feels packaged, rewrite more naturally.

Return raw JSON only: {"posts":[{"caption":"..."}]}.`;
export async function POST(req:NextRequest){try{const key=process.env.OPENAI_API_KEY;if(!key)return Response.json({error:'OpenAI captioning is not configured yet.'},{status:500});const{posts}=await req.json();if(!Array.isArray(posts)||posts.length<1||posts.length>3)return Response.json({error:'One to three posts required'},{status:400});const sb=createClient()as any,{data:{user}}=await sb.auth.getUser();if(!user)return Response.json({error:'Unauthorized'},{status:401});const ids=[...new Set(posts.flatMap((p:any)=>p.assetIds||[]).map(String))];const[{data:assets},{data:recent}]=await Promise.all([sb.from('media_assets').select('id,storage_path,file_type,ai_reason,tags').in('id',ids).eq('user_id',user.id),sb.from('posts').select('caption_option1,caption_option2,notes,created_at').eq('user_id',user.id).eq('pillar','Approved Posts').order('created_at',{ascending:false}).limit(40)]),byId=new Map((assets||[]).map((a:any)=>[a.id,a])),approved=(recent||[]).map((x:any)=>String(x.caption_option1||'').trim()).filter(Boolean),edits=(recent||[]).filter((x:any)=>String(x.notes||'').startsWith('Approved Post Bank')&&x.caption_option1&&x.caption_option2&&x.caption_option1!==x.caption_option2).slice(0,12).map((x:any)=>`AI: ${x.caption_option2}\nFINAL: ${x.caption_option1}`).join('\n---\n'),mediaSets=posts.map((p:any)=>{const media=(p.assetIds||[]).map((id:string)=>byId.get(id)).filter(Boolean)as any[],reel=String(p.format).toLowerCase()==='reel',hints=[...new Set(media.flatMap((a:any)=>(a.tags||[]).filter((t:string)=>/^(event:|planning:)/.test(t)).map((t:string)=>t.replace(/^(event:|planning:)/,''))))];return{p,media,reel,hints}});
const strategyInput:any[]=[{role:'system',content:[{type:'input_text',text:STRATEGIST}]},{role:'user',content:[{type:'input_text',text:`RECENT APPROVED BANK:\n${approved.length?approved.join('\n'):'None yet.'}` }]}];mediaSets.forEach((s:any,i:number)=>{const content:any[]=[{type:'input_text',text:`POST ${i+1}. Format: ${s.p.format}. ${s.reel?`Whole-video context: ${s.media.map((a:any)=>a.ai_reason).filter(Boolean).join(' | ')||'No stored context.'}`:'Use current attached images as visual truth.'} Event hints: ${s.hints.join(', ')||'none'}. Decide why this is worth posting.`}];if(!s.reel)for(const a of s.media.slice(0,5))if(String(a.file_type||'').startsWith('image/'))content.push({type:'input_image',image_url:sb.storage.from('media').getPublicUrl(a.storage_path).data.publicUrl,detail:'auto'});strategyInput.push({role:'user',content})});const strategy=await ask(key,strategyInput,900);if(!Array.isArray(strategy.posts)||strategy.posts.length!==posts.length)throw new Error('Invalid strategy returned');
const writerInput:any[]=[{role:'system',content:[{type:'input_text',text:WRITER}]},{role:'user',content:[{type:'input_text',text:`RECENT APPROVED CAPTIONS TO AVOID REPEATING:\n${approved.length?approved.join('\n'):'None yet.'}${edits?`\n\nHOW THE OWNER EDITS AI COPY:\n${edits}`:''}`}]}];mediaSets.forEach((s:any,i:number)=>{const plan=strategy.posts[i]||{},content:any[]=[{type:'input_text',text:`POST ${i+1}. Strategic purpose: ${plan.purpose||'Brand/Personality'}. Private writer brief: ${plan.brief||'Find the most natural useful thought supported by the media.'} Format: ${s.p.format}. ${s.reel?`Whole-video context: ${s.media.map((a:any)=>a.ai_reason).filter(Boolean).join(' | ')||'No stored context.'}`:'Look at the attached current images. Do not just describe them.'} Write the caption naturally. Never mention the purpose or brief.`}];if(!s.reel)for(const a of s.media.slice(0,5))if(String(a.file_type||'').startsWith('image/'))content.push({type:'input_image',image_url:sb.storage.from('media').getPublicUrl(a.storage_path).data.publicUrl,detail:'auto'});writerInput.push({role:'user',content})});const written=await ask(key,writerInput,1000);if(!Array.isArray(written.posts)||written.posts.length!==posts.length)throw new Error('Invalid captions returned');return Response.json({posts:written.posts.map((x:any,i:number)=>({caption:String(x.caption||'').trim(),purpose:String(strategy.posts[i]?.purpose||'').trim()}))})}catch(e){return Response.json({error:e instanceof Error?e.message:'Could not create review set'},{status:500})}}
