'use client'

import { useState } from 'react'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import type { User } from '@supabase/supabase-js'

interface NavItem { href:string; label:string; icon:(p:{className?:string})=>JSX.Element; badge?:string }
interface NavSubGroup { subGroup:string; items:NavItem[] }
interface NavGroup { label:string; collapsible:boolean; children:(NavItem|NavSubGroup)[] }
interface SidebarProps { user:User }

const navGroups:NavGroup[]=[
 {label:'Marketing',collapsible:true,children:[
  {href:'/marketing-events',label:'Events',icon:EventsIcon},
  {href:'/media-bank',label:'Media Bank',icon:MediaIcon},
  {subGroup:'Social Media',items:[{href:'/quick-post',label:'Create New Post',icon:QuickPostIcon},{href:'/content-bank',label:'Content Bank',icon:ContentIcon},{href:'/calendar',label:'Calendar',icon:CalendarIcon},{href:'/pillars',label:'Pillars',icon:PillarsIcon}]},
  {subGroup:'Hiring Ads',items:[]},{subGroup:'Promotions',items:[]}
 ]},
 {label:'Operations',collapsible:true,children:[{href:'/recipes',label:'Recipes',icon:RecipesIcon},{href:'/training',label:'Training Manuals',icon:TrainingIcon},{href:'/events',label:'Events & Pack Lists',icon:EventsIcon}]},
 {label:'Settings',collapsible:true,children:[{href:'/settings',label:'Settings',icon:SettingsIcon}]}
]
function isSubGroup(i:NavItem|NavSubGroup):i is NavSubGroup{return'subGroup'in i}function allHrefsInGroup(g:NavGroup){return g.children.flatMap(c=>isSubGroup(c)?c.items.map(i=>i.href):[c.href])}
export default function Sidebar({user}:SidebarProps){const pathname=usePathname(),router=useRouter(),[mobileOpen,setMobileOpen]=useState(false),[signingOut,setSigningOut]=useState(false),[collapsedGroups,setCollapsedGroups]=useState<Record<string,boolean>>({});const toggleGroup=(k:string)=>setCollapsedGroups(p=>({...p,[k]:!p[k]}));const isActive=(h:string)=>pathname===h||(h!=='/dashboard'&&pathname.startsWith(h));async function handleSignOut(){setSigningOut(true);await createClient().auth.signOut();router.push('/login')}const displayName=user.email?.split('@')[0]??'You',initial=displayName.charAt(0).toUpperCase();function NavLink({href,label,icon:Icon,badge,indent}:NavItem&{indent?:boolean}){const active=isActive(href);return <Link href={href} onClick={()=>setMobileOpen(false)} className={`flex items-center gap-3 rounded-lg font-medium transition-colors ${indent?'pl-7 pr-3 py-1.5 text-xs':'px-3 py-2.5 text-sm'} ${active?'bg-stone-800 text-white':'text-stone-400 hover:text-stone-200 hover:bg-stone-800/60'}`}><Icon className={`flex-shrink-0 ${indent?'w-3.5 h-3.5':'w-4 h-4'} ${active?'text-ember-400':'text-stone-500'}`}/>{label}{badge&&<span className="ml-auto text-xs font-medium text-ember-400 bg-ember-950/60 px-1.5 py-0.5 rounded">{badge}</span>}</Link>}
const SidebarContent=()=> <div className="flex flex-col h-full"><div className="px-5 py-5 border-b border-stone-800"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-lg bg-ember-600 flex items-center justify-center flex-shrink-0"><FlameIcon className="w-4.5 h-4.5 text-white"/></div><div><p className="text-white font-semibold text-sm leading-none">Fireova Hub</p><p className="text-stone-500 text-xs mt-0.5">Content OS</p></div></div></div><nav className="flex-1 px-3 py-3 overflow-y-auto sidebar-nav">{navGroups.map(group=>{const gc=!!collapsedGroups[group.label],hrefs=allHrefsInGroup(group);return <div key={group.label} className="mb-1"><button onClick={()=>toggleGroup(group.label)} className="w-full flex items-center justify-between px-3 py-2 rounded-lg text-stone-200 hover:text-white hover:bg-stone-800/40"><span className="text-sm font-bold tracking-wide">{group.label}</span><span className={`text-stone-600 ${gc?'-rotate-90':''}`}>⌄</span></button>{!gc&&<div className="space-y-0.5 mt-0.5">{group.children.map((child,i)=>isSubGroup(child)?<div key={`${group.label}-${child.subGroup}`}><button onClick={()=>toggleGroup(`${group.label}::${child.subGroup}`)} className="w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-stone-400 hover:text-stone-200 hover:bg-stone-800/60"><span className="flex items-center gap-3"><FolderIcon className="w-4 h-4 text-stone-500"/>{child.subGroup}</span><span className="text-stone-600">⌄</span></button>{!collapsedGroups[`${group.label}::${child.subGroup}`]&&child.items.map(item=><NavLink key={item.href}{...item} indent/>)}</div>:<NavLink key={child.href}{...child}/>)}</div>}</div>})}</nav><div className="border-t border-stone-800 p-3"><div className="flex items-center gap-2 px-2 py-2"><div className="w-8 h-8 rounded-full bg-ember-700 text-white flex items-center justify-center text-xs font-semibold">{initial}</div><p className="text-xs text-stone-300 truncate flex-1">{user.email}</p></div><button onClick={handleSignOut} disabled={signingOut} className="w-full flex items-center gap-3 px-3 py-2 text-sm text-stone-500 hover:text-stone-300"><SignOutIcon className="w-4 h-4"/>{signingOut?'Signing out…':'Sign out'}</button></div></div>;
return <><aside className="hidden md:block fixed inset-y-0 left-0 w-64 bg-stone-950 z-40"><SidebarContent/></aside><button onClick={()=>setMobileOpen(true)} className="md:hidden fixed top-4 left-4 z-30 w-10 h-10 rounded-lg bg-stone-950 text-white">☰</button>{mobileOpen&&<><button aria-label="Close menu" onClick={()=>setMobileOpen(false)} className="fixed inset-0 bg-black/40 z-40 md:hidden"/><aside className="fixed inset-y-0 left-0 w-72 bg-stone-950 z-50 md:hidden"><SidebarContent/></aside></>}</>}
function I({className}:{className?:string}){return <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.7"><rect x="4" y="4" width="16" height="16" rx="2"/></svg>}function FlameIcon(p:{className?:string}){return <I {...p}/>}function MediaIcon(p:{className?:string}){return <I {...p}/>}function QuickPostIcon(p:{className?:string}){return <I {...p}/>}function ContentIcon(p:{className?:string}){return <I {...p}/>}function CalendarIcon(p:{className?:string}){return <I {...p}/>}function PillarsIcon(p:{className?:string}){return <I {...p}/>}function RecipesIcon(p:{className?:string}){return <I {...p}/>}function TrainingIcon(p:{className?:string}){return <I {...p}/>}function EventsIcon(p:{className?:string}){return <I {...p}/>}function SettingsIcon(p:{className?:string}){return <I {...p}/>}function FolderIcon(p:{className?:string}){return <I {...p}/>}function SignOutIcon(p:{className?:string}){return <I {...p}/>}
