'use client';

import { useMemo, useRef, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { appendManualDraft, approveOnce, restoreManualDrafts, runExclusive, type ManualAsset as Asset, type ManualKind as Kind, type ManualPost as Post, type ManualSlot as Slot } from '@/lib/manual-content-drafts';

const tagValues=(a:Asset,prefix:string)=>(a.tags||[]).filter(t=>t.startsWith(prefix)).map(t=>t.slice(prefix.length).trim());
const credit=(a:Asset)=>tagValues(a,'photographer:')[0]||'';
const isVideo=(a:Asset)=>a.file_type.startsWith('video/');
const visibleMatch=(a:Asset,qRaw:string)=>{const q=qRaw.trim().toLowerCase();if(!q)return true;const subjects=tagValues(a,'subject:').map(s=>s.toLowerCase()),people=tagValues(a,'person:').map(s=>s.toLowerCase()),credits=tagValues(a,'photographer:').map(s=>s.toLowerCase());if(q==='pizza'){const bad=/oven|shirt|logo|sign|signage|tent|truck|box|menu|text|brand/;return subjects.some(s=>!bad.test(s)&&(s==='pizza'||s==='pizzas'||s.endsWith(' pizza')||/pizza (slice|slices|food|crust|topping)/.test(s)))}return[...subjects,...people,...credits].some(s=>s.includes(q))};

export default function WeeklyContentPersistent({initialAssets,savedSlots=[]}:{initialAssets:Asset[];savedSlots?:Slot[]}){
  const supabase=useMemo(()=>createClient()as any,[]),restored=useMemo(()=>restoreManualDrafts(savedSlots,initialAssets),[savedSlots,initialAssets]);
  const[pool,setPool]=useState(initialAssets),[posts,setPosts]=useState(restored.posts),[captions,setCaptions]=useState<Record<string,string>>(restored.captions),[originals,setOriginals]=useState<Record<string,string>>(restored.originals);
  const[draftCaption,setDraftCaption]=useState(''),[draftKind,setDraftKind]=useState<Kind>('Photo'),[draftMedia,setDraftMedia]=useState<Asset[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[approving,setApproving]=useState<Record<string,boolean>>({}),[errors,setErrors]=useState<Record<string,string>>({});
  const uploadRef=useRef<HTMLInputElement>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),savingRef=useRef(false),approvalLocks=useRef(new Set<string>()),approvalSucceeded=useRef(new Set<string>()),url=(a:Asset)=>supabase.storage.from('media').getPublicUrl(a.storage_path).data.publicUrl;
  const visibleAssets=useMemo(()=>pool.filter(a=>visibleMatch(a,query)),[pool,query]);

  async function persist(nextPosts=posts,nextCaptions=captions,nextOriginals=originals){
    const slots=nextPosts.filter(p=>nextCaptions[p.id]?.trim()).map(p=>({assetIds:p.media.map(a=>a.id),kind:p.kind,caption:nextCaptions[p.id].trim(),originalCaption:(nextOriginals[p.id]||nextCaptions[p.id]).trim(),purpose:p.purpose}));
    const response=await fetch('/api/review-queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slots}),cache:'no-store'}),data=await response.json().catch(()=>({}));
    if(!response.ok||!data.ok)throw new Error(data.error||'Could not save review queue');
  }
  function queueCaptionSave(next:Record<string,string>){if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>void persist(posts,next,originals).catch(e=>setErrors(v=>({...v,queue:e instanceof Error?e.message:'Could not save caption'}))),700)}
  function chooseAsset(asset:Asset){setDraftMedia(current=>{if(current.some(a=>a.id===asset.id))return current.filter(a=>a.id!==asset.id);if(isVideo(asset)){setDraftKind('Reel');return[asset]}const next=[...current.filter(a=>!isVideo(a)),asset].slice(0,10);setDraftKind(next.length>1?'Carousel':'Photo');return next})}
  function moveDraft(index:number,direction:-1|1){setDraftMedia(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
  async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);try{const added:Asset[]=[];for(const file of Array.from(files)){const body=new FormData();body.append('file',file);const response=await fetch('/api/media/upload',{method:'POST',body}),data=await response.json().catch(()=>({}));if(!response.ok||!data.asset)throw new Error(data.error||'Could not upload media');added.push(data.asset)}setPool(v=>[...added,...v]);setDraftMedia(current=>{const combined=[...current,...added];if(combined.some(isVideo)){setDraftKind('Reel');return[combined.find(isVideo)!]}setDraftKind(combined.length>1?'Carousel':'Photo');return combined.slice(0,10)})}catch(e){setErrors(v=>({...v,composer:e instanceof Error?e.message:'Could not upload media'}))}finally{setBusy(false);if(uploadRef.current)uploadRef.current.value=''}}
  async function saveDraft(){const caption=draftCaption.trim();if(!caption||!draftMedia.length){setErrors(v=>({...v,composer:'Add a caption and choose at least one photo or video.'}));return}await runExclusive(savingRef,async()=>{setBusy(true);try{const kind:Kind=draftMedia.some(isVideo)?'Reel':draftMedia.length>1?'Carousel':draftKind,id=`manual-${Date.now()}-${draftMedia.map(a=>a.id).join('-')}`,post:Post={id,media:draftMedia,kind,purpose:'Draft'},next=appendManualDraft({posts,captions,originals},post,caption);await persist(next.posts,next.captions,next.originals);setPosts(next.posts);setCaptions(next.captions);setOriginals(next.originals);setDraftCaption('');setDraftMedia([]);setDraftKind('Photo');setQuery('');setErrors(v=>({...v,composer:'',queue:''}))}catch(e){setErrors(v=>({...v,composer:e instanceof Error?e.message:'Could not save draft'}))}finally{setBusy(false)}})}
  async function removeDraft(post:Post){const nextPosts=posts.filter(p=>p.id!==post.id),nextCaptions={...captions},nextOriginals={...originals};delete nextCaptions[post.id];delete nextOriginals[post.id];await persist(nextPosts,nextCaptions,nextOriginals);setPosts(nextPosts);setCaptions(nextCaptions);setOriginals(nextOriginals)}
  async function approve(post:Post){const caption=captions[post.id]?.trim();if(!caption||post.media.some(a=>a.missing)||approvalLocks.current.has(post.id))return;approvalLocks.current.add(post.id);setApproving(v=>({...v,[post.id]:true}));try{await approveOnce(post.id,approvalSucceeded.current,async()=>{const credits=[...new Set(post.media.map(credit).filter(Boolean))],response=await fetch('/api/weekly-post/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetIds:post.media.map(a=>a.id),caption:[caption,...credits].join('\n\nPhoto: ').trim(),originalCaption:originals[post.id]||caption,format:post.kind})}),data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Could not approve')},async()=>removeDraft(post))}catch(e){setErrors(v=>({...v,[post.id]:e instanceof Error?e.message:'Could not approve'}))}finally{approvalLocks.current.delete(post.id);setApproving(v=>({...v,[post.id]:false}))}}

  return <section>
    <input ref={uploadRef} type="file" accept="image/*,video/*" multiple className="hidden" onChange={e=>void upload(e.target.files)}/>
    <div className="rounded-2xl border bg-white p-5 shadow-sm">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">Create content</p><h2 className="mt-1 text-2xl font-semibold text-stone-900">Build a draft for review</h2><p className="mt-1 text-sm text-stone-500">Choose and arrange your media, then write the caption together. Nothing publishes automatically.</p>
      <label className="mt-5 block text-xs font-semibold uppercase tracking-wide text-stone-600" htmlFor="draft-caption">Caption</label><textarea id="draft-caption" value={draftCaption} onChange={e=>setDraftCaption(e.target.value)} rows={5} placeholder="Write your caption…" className="mt-2 w-full resize-y rounded-xl border border-stone-200 px-3 py-2.5 text-sm leading-6 outline-none focus:border-stone-400"/>
      <div className="mt-4 flex flex-wrap items-center gap-2">{(['Photo','Carousel','Reel']as Kind[]).map(kind=><button key={kind} type="button" onClick={()=>{setDraftKind(kind);if(kind==='Reel')setDraftMedia(v=>v.filter(isVideo).slice(0,1));else setDraftMedia(v=>v.filter(a=>!isVideo(a)).slice(0,kind==='Photo'?1:10))}} className={`rounded-lg px-3 py-2 text-xs font-semibold ${draftKind===kind?'bg-orange-600 text-white':'bg-stone-100 text-stone-700'}`}>{kind}</button>)}<button type="button" onClick={()=>uploadRef.current?.click()} className="ml-auto rounded-lg bg-stone-100 px-3 py-2 text-xs font-semibold text-stone-700">{busy?'Working…':'Upload media'}</button></div>
      {draftMedia.length>0&&<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 md:grid-cols-6">{draftMedia.map((asset,index)=><div key={asset.id} className="overflow-hidden rounded-lg border bg-stone-50"><div className="aspect-square">{isVideo(asset)?<video src={url(asset)} muted className="h-full w-full object-cover"/>:<img src={url(asset)} alt="" className="h-full w-full object-cover"/>}</div><div className="flex items-center justify-center gap-1 p-1"><button aria-label="Move media left" disabled={index===0} onClick={()=>moveDraft(index,-1)} className="px-2 text-sm disabled:opacity-25">←</button><span className="text-[10px] text-stone-500">{index+1}</span><button aria-label="Move media right" disabled={index===draftMedia.length-1} onClick={()=>moveDraft(index,1)} className="px-2 text-sm disabled:opacity-25">→</button><button aria-label="Remove media" onClick={()=>chooseAsset(asset)} className="px-2 text-sm text-stone-500">×</button></div></div>)}</div>}
      <div className="mt-5 border-t pt-5"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-stone-900">Media Bank</h3><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search filenames, tags, or subjects" className="min-w-56 flex-1 rounded-lg border border-stone-200 px-3 py-2 text-sm outline-none focus:border-stone-400"/></div><div className="mt-3 grid max-h-80 grid-cols-3 gap-2 overflow-y-auto sm:grid-cols-5 md:grid-cols-7">{visibleAssets.map(asset=>{const selected=draftMedia.some(a=>a.id===asset.id);return <button key={asset.id} onClick={()=>chooseAsset(asset)} className={`relative aspect-square overflow-hidden rounded-lg border-2 ${selected?'border-orange-500':'border-transparent'}`}>{isVideo(asset)?<video src={url(asset)} muted className="h-full w-full object-cover"/>:<img src={url(asset)} alt="" className="h-full w-full object-cover"/>}{selected&&<span className="absolute right-1 top-1 rounded-full bg-orange-600 px-1.5 py-0.5 text-[10px] text-white">✓</span>}</button>})}</div></div>
      {errors.composer&&<p className="mt-3 text-sm text-red-600">{errors.composer}</p>}<div className="mt-5 flex justify-end"><button disabled={busy||!draftCaption.trim()||!draftMedia.length} onClick={()=>void saveDraft()} className="rounded-xl bg-orange-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Save for review</button></div>
    </div>
    <div className="mt-6"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">Review queue</p><h2 className="mt-1 text-xl font-semibold text-stone-900">Saved drafts</h2></div><span className="text-sm text-stone-500">{posts.length} draft{posts.length===1?'':'s'}</span></div>{errors.queue&&<p className="mt-2 text-sm text-red-600">{errors.queue}</p>}
      {posts.length===0?<div className="mt-3 rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-stone-500">Your saved drafts will appear here for explicit review.</div>:<div className="mt-3 grid gap-4 lg:grid-cols-3">{posts.map(post=>{const hasMissing=post.media.some(a=>a.missing);return <div key={post.id} className="self-start overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-700">{post.kind}</p><span className="text-[11px] text-stone-500">Draft</span></div><div className={`grid gap-1 bg-stone-100 p-1 ${post.media.length>1?'grid-cols-3':'grid-cols-1'}`}>{post.media.map(asset=><div key={asset.id} className={`${post.media.length>1?'aspect-square':'aspect-[4/3]'} overflow-hidden rounded-md bg-white`}>{asset.missing?<div className="flex h-full items-center justify-center p-3 text-center text-xs text-stone-500">Media unavailable<br/>{asset.id}</div>:isVideo(asset)?<video src={url(asset)} muted playsInline controls className="h-full w-full bg-black object-cover"/>:<img src={url(asset)} alt="" className="h-full w-full object-cover"/>}</div>)}</div><div className="p-5">{hasMissing&&<p className="mb-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">This draft is preserved, but unavailable media must be restored before approval.</p>}<textarea value={captions[post.id]||''} onChange={e=>{const next={...captions,[post.id]:e.target.value};setCaptions(next);queueCaptionSave(next)}} rows={4} className="w-full resize-y rounded-xl border border-stone-200 px-3 py-2.5 text-sm leading-6 text-stone-700 outline-none focus:border-stone-400"/>{errors[post.id]&&<p className="mt-2 text-xs text-red-600">{errors[post.id]}</p>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={hasMissing||Boolean(approving[post.id])||!captions[post.id]?.trim()} onClick={()=>void approve(post)} className="rounded-lg bg-orange-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{approving[post.id]?'Approving…':approvalSucceeded.current.has(post.id)?'Finish approval':'Approve post'}</button><button onClick={()=>void removeDraft(post).catch(e=>setErrors(v=>({...v,[post.id]:e instanceof Error?e.message:'Could not remove draft'})))} className="rounded-lg bg-stone-100 px-3 py-2 text-xs font-medium text-stone-700">Remove draft</button></div></div></div>})}</div>}
    </div>
  </section>;
}
