import { NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';

type Asset={id:string;storage_path:string;file_type:string;ai_reason?:string|null;tags?:string[]|null;created_at?:string};
type Kind='Photo'|'Reel'|'Carousel';
type Candidate={assetIds:string[];kind:Kind;summary:string;family:string};
const values=(a:Asset,p:string)=>(a.tags||[]).filter(t=>t.startsWith(p)).map(t=>t.slice(p.length).toLowerCase());
const subject=(a:Asset)=>values(a,'primary:')[0]||values(a,'subject:')[0]||'';
function family(a:Asset){const s=subject(a);if(/charcuterie|grazing|salami|prosciutto|cheese|cracker/.test(s))return'charcuterie';if(/dessert|cake|cannoli|tiramisu|cookie|sweet/.test(s))return'dessert';if(/pizza|dough|stretch|toss/.test(s)&&!/oven|truck|sign/.test(s))return'pizza';if(/oven|fire|truck/.test(s))return'oven';if(/wedding|bride|groom|couple/.test(s))return'wedding';if(/salad/.test(s))return'salad';if(/shrimp|ahi|tuna|appetizer|small bite/.test(s))return'small-bites';if(/team|staff|chef|person|people/.test(s))return'team';return s||'other'}
function summary(a:Asset){const tags=(a.tags||[]).filter(t=>/^(primary:|subject:|event:|planning:)/.test(t)).slice(0,8).join(', ');return [tags,a.ai_reason||''].filter(Boolean).join(' | ').slice(0,500)}
function candidates(assets:Asset[]){const out:Candidate[]=[],used=new Set<string>();for(const video of assets.filter(a=>a.file_type.startsWith('video/')).slice(0,8))out.push({assetIds:[video.id],kind:'Reel',family:family(video),summary:summary(video)});const photos=assets.filter(a=>a.file_type.startsWith('image/'));for(const seed of photos){if(used.has(seed.id))continue;const f=family(seed),group=[seed,...photos.filter(a=>a.id!==seed.id&&!used.has(a.id)&&family(a)===f).slice(0,4)];group.forEach(a=>used.add(a.id));out.push({assetIds:group.map(a=>a.id),kind:group.length>1?'Carousel':'Photo',family:f,summary:group.map(summary).filter(Boolean).join(' || ').slice(0,900)});if(out.length>=24)break}return out}
function outputText(d:any){if(typeof d?.output_text==='string')return d.output_text.trim();for(const x of d?.output||[])for(const c of x?.content||[])if(c?.type==='output_text')return String(c.text||'').trim();return''}
async function ask(key:string,input:any[],tokens=1200){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6',reasoning:{effort:'medium'},input,max_output_tokens:tokens})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'OpenAI request failed');return JSON.parse(outputText(d).replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim())}
const STRATEGY=`You are Fireova Pizza's social media strategist. Choose posts BEFORE captions are written. Fireova needs a balanced approved content bank, not three random event posts. Strategic purposes: Education, Experience, Food, Wedding/Event Inspiration, Brand/Personality, Team/Behind the Scenes. Team is occasional and should focus on process, not employee personalities or names. Prefer carousels/reels over weak standalone photos. A single photo must be genuinely strong enough to carry a post. Avoid choosing multiple candidates that tell basically the same story. Use recent approved captions to identify what is already overrepresented. Choose media whose supplied metadata can honestly support the purpose. Return JSON only: {"choices":[{"candidate":0,"purpose":"Education","reason":"..."}]}.`;
const WRITER=`You write Fireova Pizza Instagram captions. Write like the owner/team: warm, conversational, simple, confident, humble. No em dash. Never say pie. No employee names. Usually 0-1 emoji. Do not describe the image just to prove you saw it. Do not manufacture humor. The STRATEGIC PURPOSE is the reason the post exists; fulfill it naturally. Education should teach something a potential customer would actually want to know. Experience should explain what guests or clients experience. Food should make the offering clear/appetizing. Wedding/Event Inspiration should give couples/event planners an idea or moment worth saving. Brand/Personality can be simple and human. Team/Behind the Scenes should explain the work/process, not spotlight an employee. For Photos/Carousels, only state concrete visual facts supported by attached current images. For Reels, whole-video context may be used. Return JSON only: {"posts":[{"caption":"..."}]}.`;
export async function POST(req:NextRequest){try{const key=process.env.OPENAI_API_KEY;if(!key)return Response.json({error:'OpenAI captioning is not configured.'},{status:500});const body=await req.json().catch(()=>({})),count=Math.max(1,Math.min(3,Number(body.count)||3)),exclude=new Set<string>((body.excludeAssetIds||[]).map(String));const sb=createClient() as any,{data:{user}}=await sb.auth.getUser();if(!user)return Response.json({error:'Unauthorized'},{status:401});const[{data:all},{data:approved}]=await Promise.all([sb.from('media_assets').select('id,storage_path,file_type,ai_reason,tags,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(250),sb.from('posts').select('id,caption_option1,created_at').eq('user_id',user.id).eq('pillar','Approved Posts').order('created_at',{ascending:false}).limit(30)]);let assets=(all||[]).filter((a:Asset)=>!exclude.has(a.id));if(approved?.length){const ids=approved.map((p:any)=>p.id),{data:links}=await sb.from('post_media').select('post_id,asset_id').in('post_id',ids),times=new Map(approved.map((p:any)=>[p.id,new Date(p.created_at).getTime()])),last=new Map<string,number>();for(const l of links||[]){const t=times.get(l.post_id)||0;if(t>(last.get(l.asset_id)||0))last.set(l.asset_id,t)}assets=[...assets].sort((a:Asset,b:Asset)=>{const x=last.get(a.id),y=last.get(b.id);if(x==null&&y!=null)return-1;if(x!=null&&y==null)return 1;if(x!=null&&y!=null&&x!==y)return x-y;return new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime()})}
const pool=candidates(assets);if(!pool.length)return Response.json({error:'No media available'},{status:400});const recent=(approved||[]).map((p:any)=>String(p.caption_option1||'').trim()).filter(Boolean).slice(0,20);const strategy=await ask(key,[{role:'system',content:[{type:'input_text',text:STRATEGY}]},{role:'user',content:[{type:'input_text',text:`Need ${count} new post${count===1?'':'s'}. RECENT APPROVED:\n${recent.join('\n')||'None yet.'}\n\nCANDIDATES:\n${pool.map((c,i)=>`${i}. ${c.kind} | ${c.family} | ${c.summary}`).join('\n')}`}]}],900);const raw=Array.isArray(strategy.choices)?strategy.choices:[],picked:any[]=[],seen=new Set<number>();for(const choice of raw){const i=Number(choice.candidate);if(Number.isInteger(i)&&pool[i]&&!seen.has(i)){picked.push({...pool[i],purpose:String(choice.purpose||'Brand/Personality')});seen.add(i)}if(picked.length===count)break}for(let i=0;picked.length<count&&i<pool.length;i++)if(!seen.has(i)){picked.push({...pool[i],purpose:'Brand/Personality'});seen.add(i)}
const byId=new Map(assets.map((a:Asset)=>[a.id,a])),writer:any[]=[{role:'system',content:[{type:'input_text',text:WRITER}]}];for(let i=0;i<picked.length;i++){const p=picked[i],media=p.assetIds.map((id:string)=>byId.get(id)).filter(Boolean) as Asset[],content:any[]=[{type:'input_text',text:`POST ${i+1}. Strategic purpose: ${p.purpose}. Format: ${p.kind}. ${p.kind==='Reel'?`Whole-video context: ${media.map(a=>a.ai_reason).filter(Boolean).join(' | ')||'none'}`:'Use attached current images as visual truth.'}`}];if(p.kind!=='Reel')for(const a of media.slice(0,5))content.push({type:'input_image',image_url:sb.storage.from('media').getPublicUrl(a.storage_path).data.publicUrl,detail:'auto'});writer.push({role:'user',content})}writer.push({role:'user',content:[{type:'input_text',text:`Write exactly ${picked.length} captions in order. Each must fulfill its assigned purpose and sound natural. Raw JSON only.`}]});const written=await ask(key,writer,1100);if(!Array.isArray(written.posts)||written.posts.length!==picked.length)throw new Error('Invalid captions returned');const suggestions=picked.map((p:any,i:number)=>({assetIds:p.assetIds,kind:p.kind,purpose:p.purpose,caption:String(written.posts[i]?.caption||'').trim()}));if(suggestions.some((s:any)=>!s.caption))throw new Error('Caption came back empty');return Response.json({ok:true,suggestions})}catch(e){return Response.json({error:e instanceof Error?e.message:'Could not create strategic suggestions'},{status:500})}}
