import Anthropic from '@anthropic-ai/sdk'
import { NextResponse } from 'next/server'
import sharp from 'sharp'
import { createClient } from '@/lib/supabase/server'

function editedFilename(name:string){return `${name.replace(/\.[^.]+$/,'')}-polished.jpg`}
type Recipe={brightness:number;saturation:number;contrast:number;gamma:number;sharpen:number;reason:string}
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n))

export async function POST(_request:Request,{params}:{params:{id:string}}){
 const supabase=createClient() as any;const{data:{user}}=await supabase.auth.getUser();if(!user||user.id==='dev')return NextResponse.json({error:'Unauthorized'},{status:401})
 const{data:asset,error:assetError}=await supabase.from('media_assets').select('*').eq('id',params.id).eq('user_id',user.id).single();if(assetError||!asset)return NextResponse.json({error:assetError?.message||'Media asset not found'},{status:404});if(!String(asset.file_type||'').startsWith('image/'))return NextResponse.json({error:'Photo polish only supports images.'},{status:400})
 const{data:original,error:downloadError}=await supabase.storage.from('media').download(asset.storage_path);if(downloadError||!original)return NextResponse.json({error:downloadError?.message||'Could not load original photo.'},{status:500});const input=Buffer.from(await original.arrayBuffer());const imageUrl=supabase.storage.from('media').getPublicUrl(asset.storage_path).data.publicUrl
 let recipe:Recipe={brightness:1.06,saturation:1.04,contrast:1.06,gamma:1,sharpen:.9,reason:'Balanced professional finishing.'}
 const apiKey=process.env.ANTHROPIC_API_KEY
 if(apiKey){try{const client=new Anthropic({apiKey});const response=await client.messages.create({model:'claude-sonnet-4-5',max_tokens:350,system:`You are a professional event and food photo finishing assistant. Analyze the actual image and choose conservative global adjustments that visibly improve it while preserving the real event. Never invent/remove objects, alter people, change food/decor, or make colors unnatural. Return ONLY JSON: {"brightness":1.0,"saturation":1.0,"contrast":1.0,"gamma":1.0,"sharpen":0.8,"reason":"..."}. Allowed ranges: brightness .92-1.16, saturation .90-1.14, contrast .94-1.14, gamma .90-1.10, sharpen .4-1.4. If foreground is dark against a bright background, favor moderate brightness/gamma rather than blowing highlights. If whites/food have a warm or yellow cast, reduce saturation modestly rather than exaggerating it. Aim for a professional natural event photograph, not a filter.`,messages:[{role:'user',content:[{type:'image',source:{type:'url',url:imageUrl}},{type:'text',text:`Create a finishing recipe for ${asset.filename}. Existing reviewer note: ${asset.ai_reason||'none'}. Existing edit suggestion: ${asset.ai_edit_suggestion||'none'}.`}]}]});const block=response.content.find(b=>b.type==='text');if(block&&block.type==='text'){const parsed=JSON.parse(block.text.replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim());recipe={brightness:clamp(Number(parsed.brightness)||1,.92,1.16),saturation:clamp(Number(parsed.saturation)||1,.90,1.14),contrast:clamp(Number(parsed.contrast)||1,.94,1.14),gamma:clamp(Number(parsed.gamma)||1,.90,1.10),sharpen:clamp(Number(parsed.sharpen)||.8,.4,1.4),reason:String(parsed.reason||'Adaptive professional finishing.')}}}catch{}}
 let output:Buffer;try{let pipeline=sharp(input).rotate().modulate({brightness:recipe.brightness,saturation:recipe.saturation}).gamma(recipe.gamma);const intercept=128*(1-recipe.contrast);pipeline=pipeline.linear(recipe.contrast,intercept).sharpen({sigma:recipe.sharpen});output=await pipeline.jpeg({quality:94,chromaSubsampling:'4:4:4',mozjpeg:true}).toBuffer()}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Photo processing failed.'},{status:500})}
 const newId=crypto.randomUUID(),folder=asset.storage_path.includes('/')?asset.storage_path.slice(0,asset.storage_path.lastIndexOf('/')):`${user.id}/polished`,newName=editedFilename(asset.filename||'photo.jpg'),newPath=`${folder}/${newId}-${newName}`;const{error:uploadError}=await supabase.storage.from('media').upload(newPath,output,{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(uploadError)return NextResponse.json({error:uploadError.message},{status:500})
 const tags=Array.from(new Set([...(asset.tags||[]),`edited-from:${asset.id}`,'professional-polish']));const row={id:newId,user_id:user.id,filename:newName,storage_path:newPath,file_type:'image/jpeg',size_bytes:output.length,tags,notes:`Adaptive professional polish: ${recipe.reason}`,created_at:new Date().toISOString(),folder_id:asset.folder_id??null,ai_status:null,ai_reason:null,ai_categories:asset.ai_categories??[],ai_post_uses:asset.ai_post_uses??[],ai_edit_suggestion:null};const{error:insertError}=await supabase.from('media_assets').insert(row);if(insertError){await supabase.storage.from('media').remove([newPath]);return NextResponse.json({error:insertError.message},{status:500})}
 const{data:eventSource}=await supabase.from('event_media').select('event_id,media_kind').eq('id',asset.id).eq('user_id',user.id).maybeSingle();if(eventSource?.event_id)await supabase.from('event_media').insert({id:newId,user_id:user.id,event_id:eventSource.event_id,storage_path:newPath,file_name:newName,file_type:'image/jpeg',media_kind:'photo',size_bytes:output.length,thumbnail_path:null,preview_url:supabase.storage.from('media').getPublicUrl(newPath).data.publicUrl,checksum:null,metadata:{editedFrom:asset.id,editType:'adaptive-professional-polish',recipe}})
 return NextResponse.json({original:{id:asset.id,filename:asset.filename,storage_path:asset.storage_path},edited:{...row,public_url:supabase.storage.from('media').getPublicUrl(newPath).data.publicUrl},recipe})
}
