export const FIREOVA_CAROUSEL_VERIFY = `CAROUSEL ONLY: Treat all supplied images as one swipe story. Inspect every slide in order. The cover matters, but do not let the cover erase what later slides add. Identify the strongest shared story across the whole set.

CRITICAL EVENT-TRUTH RULE: Never assume carousel slides were photographed at the same event, wedding, venue, or day unless the supplied evidence explicitly proves that. Visual similarity, the same Fireova uniforms, pizza, ovens, tents, wedding attire, or the fact that the images look like they belong together is NOT proof of one event. If event/date identity is not explicitly verified, treat the carousel as a themed collection assembled from potentially different events. In that case, the story must be timeless/plural/collection-based, such as recurring Fireova wedding moments, team + pizza + couples, or favorite kinds of moments. Never use or imply a shared timeline with phrases such as "that day," "this wedding," "at their wedding," "the newlyweds," "later that night," "after we made," "we made a lot of pizza that day," or any cause-and-effect sequence across slides.

Only describe a single-event narrative when the metadata explicitly establishes that ALL slides share the same event identity. Otherwise, do not connect one pictured couple to food/team photos as if Fireova made that food for that couple.

If the set moves from food to team/service to guests/couples enjoying food but event identity is unverified, the story is a CROSS-EVENT THEME about the kinds of moments Fireova gets to be part of, not one wedding story. If it moves through prep, team, oven and finished food but event identity is unverified, it may represent the recurring Fireova process in general, but never "that day." Do not invent details. If the slides do not form a coherent thematic story, mark valid=false. In visual_facts, explicitly state whether same-event identity is VERIFIED or UNVERIFIED and summarize what the beginning, middle and end show.`;

export const FIREOVA_CAROUSEL_WRITE = `CAROUSEL ONLY: Write for the whole swipe, not one slide. The caption must still make sense under the cover, but it should become more meaningful after seeing every image. Find the human thought created by the sequence.

FACTUAL SAFETY RULE: If same-event identity is UNVERIFIED, write as a themed collection. Never invent one day, one wedding, one couple's menu, or a timeline. Do not say "that day," "this wedding," "their wedding," "the newlyweds," "later," "after," or otherwise imply the slides happened together. Use plural or timeless language when needed. A couple shown on later slides can be described as a bride and groom / couples / wedding moments only if visually supported, but do not connect them to food or team images as their specific event unless verified.

Do not reduce a carousel containing pizza + Fireova team + a couple eating pizza to "newlyweds with a plate of pizza." Do not reduce a prep/team/oven/finished-pizza sequence to "pizza day starts with dough." Avoid mechanically narrating each slide. React to what the whole set captures: the people, work, food, celebration, or progression that connects the images. Keep Fireova humble: warm pride is good, self-congratulation is not. Before returning, silently ask: (1) does this fit the first, middle, AND last slide? (2) did I accidentally invent a shared event/day/timeline? If either answer is wrong, rewrite.`;
