import test from 'node:test';
import assert from 'node:assert/strict';
// Node 24 executes this TypeScript test directly; TypeScript's project config
// intentionally does not enable extension imports for application source.
// @ts-expect-error Node's direct TypeScript runner requires the explicit suffix.
import { activeManualMedia, activePlanCoverage, appendManualDraft, approveOnce, beginCaptionEdit, buildApprovalPayload, cancelCaptionEdit, canApproveCaptionEdit, canInteractWithCaptionEdit, canNavigateDuringCaptionSave, chicagoPlanningAnchor, completeCaptionEdit, composeApprovedCaption, nextPlanningDate, nextPlanPosition, normalizePhotoCredits, planCells, reconcileApprovalResponse, reconcileRevision, requestRevision, restoreManualDrafts, runExclusive, serializeManualDrafts, suggestedPlanningDates, tileMedia, updateCaptionEdit, type ManualAsset, type ManualPost } from './manual-content-drafts.ts';

const assets:ManualAsset[]=[{id:'a',storage_path:'a.jpg',file_type:'image/jpeg'},{id:'b',storage_path:'b.jpg',file_type:'image/jpeg'}];

test('restores exact captions and media order',()=>{const restored=restoreManualDrafts([{assetIds:['b','a'],kind:'Carousel',caption:' exact copy ',originalCaption:'original'}],assets);assert.deepEqual(restored.posts[0].media.map(a=>a.id),['b','a']);assert.equal(restored.captions[restored.posts[0].id],' exact copy ')});
test('preserves inaccessible media as ordered placeholders',()=>{const restored=restoreManualDrafts([{assetIds:['a','gone','b'],kind:'Carousel',caption:'keep me',originalCaption:'keep me'}],assets);assert.deepEqual(restored.posts[0].media.map(a=>a.id),['a','gone','b']);assert.equal(restored.posts[0].media[1].missing,true)});
test('appends without replacing existing drafts',()=>{const old:ManualPost={id:'old',media:[assets[0]],kind:'Photo'};const added:ManualPost={id:'new',media:[assets[1]],kind:'Photo'};const next=appendManualDraft({posts:[old],captions:{old:'old copy'},originals:{old:'old copy'}},added,'new copy');assert.deepEqual(next.posts.map(p=>p.id),['old','new']);assert.equal(next.captions.old,'old copy');assert.equal(next.captions.new,'new copy')});
test('duplicate save attempts are locked and failures release the lock',async()=>{const lock={current:false};let calls=0,release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve});const first=runExclusive(lock,async()=>{calls++;await pending});const duplicate=await runExclusive(lock,async()=>{calls++});assert.equal(duplicate,false);release();assert.equal(await first,true);await assert.rejects(()=>runExclusive(lock,async()=>{throw new Error('save failed')}));assert.equal(lock.current,false);await runExclusive(lock,async()=>{calls++});assert.equal(calls,2)});
test('failed approval can retry approval',async()=>{const succeeded=new Set<string>();let approvals=0;await assert.rejects(()=>approveOnce('p',succeeded,async()=>{approvals++;throw new Error('failed')},async()=>{}));await approveOnce('p',succeeded,async()=>{approvals++},async()=>{});assert.equal(approvals,2)});
test('successful approval is not repeated when cleanup retries',async()=>{const succeeded=new Set<string>();let approvals=0,cleanups=0;await assert.rejects(()=>approveOnce('p',succeeded,async()=>{approvals++},async()=>{cleanups++;throw new Error('queue failed')}));await approveOnce('p',succeeded,async()=>{approvals++},async()=>{cleanups++});assert.equal(approvals,1);assert.equal(cleanups,2)});
test('serializes the compatible slot shape with ordered media and caption edits',()=>{const post:ManualPost={id:'p',media:[assets[1],assets[0]],kind:'Carousel',purpose:'Wedding'};assert.deepEqual(serializeManualDrafts([post],{p:'edited'},{p:'original'}),[{draftId:'p',planSlotId:'slot-p',planningDate:'',planPosition:0,assetIds:['b','a'],kind:'Carousel',caption:'edited',originalCaption:'original',purpose:'Wedding'}])});
test('tile uses first ordered asset and missing media remains visible',()=>{const restored=restoreManualDrafts([{assetIds:['gone','a'],kind:'Carousel',caption:'copy',originalCaption:'copy'}],assets);assert.equal(tileMedia(restored.posts[0])?.id,'gone');assert.equal(tileMedia(restored.posts[0])?.missing,true)});
test('stale carousel slide safely falls back across photo, reel, missing media, and another carousel',()=>{const reel:ManualAsset={id:'reel',storage_path:'reel.mp4',file_type:'video/mp4'},missing:ManualAsset={id:'gone',storage_path:'',file_type:'application/x-missing',missing:true};const posts:ManualPost[]=[{id:'photo',media:[assets[0]],kind:'Photo'},{id:'reel',media:[reel],kind:'Reel'},{id:'missing',media:[missing],kind:'Photo'},{id:'carousel',media:[assets[1],assets[0]],kind:'Carousel'}];assert.equal(activeManualMedia(posts[0],1)?.id,'a');assert.equal(activeManualMedia(posts[1],1)?.id,'reel');assert.equal(activeManualMedia(posts[2],1)?.missing,true);assert.equal(activeManualMedia(posts[3],1)?.id,'a')});
test('legacy queue slots restore without revision state',()=>{const restored=restoreManualDrafts([{assetIds:['a'],kind:'Photo',caption:'legacy',originalCaption:'legacy'}],assets);assert.equal(restored.posts[0].revision,undefined)});
test('revision notes and waiting status survive serialization and refresh',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},' More personality, please. ','caption','2026-10-04T15:22:00.000Z'),slot=serializeManualDrafts([post],{p:'caption'},{p:'caption'})[0],restored=restoreManualDrafts([slot],assets);assert.equal(restored.posts[0].revision?.note,'More personality, please.');assert.equal(restored.posts[0].revision?.status,'waiting')});
test('unchanged and interrupted caption edits remain waiting',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},'warmer','same','2026-10-04T15:22:00.000Z');assert.equal(reconcileRevision(post,'same','later').revision?.status,'waiting');assert.equal(post.revision?.status,'waiting')});
test('persisted caption change distinguishes a completed revision',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},'warmer','before','2026-10-04T15:22:00.000Z'),revised=reconcileRevision(post,'after','2026-10-04T16:00:00.000Z');assert.equal(revised.revision?.status,'revised');assert.equal(revised.revision?.note,'warmer');assert.equal(revised.revision?.revisedAt,'2026-10-04T16:00:00.000Z')});
test('caption editor exits and clears its buffer only after successful persistence',()=>{const editing=updateCaptionEdit(beginCaptionEdit('saved'),'changed');assert.deepEqual(completeCaptionEdit(true,editing),{editing:false,draft:''})});
test('caption editor preserves its buffer when persistence fails',()=>{const editing=updateCaptionEdit(beginCaptionEdit('saved'),'changed');assert.deepEqual(completeCaptionEdit(false,editing),editing)});
test('caption editing gates approval until Save or Cancel resolves it',()=>{const editing=beginCaptionEdit('saved');assert.equal(canApproveCaptionEdit(editing),false);assert.equal(canApproveCaptionEdit(completeCaptionEdit(true,editing)),true);assert.equal(canApproveCaptionEdit(cancelCaptionEdit()),true)});
test('clear then Cancel and switch then Cancel discard only the edit buffer',()=>{const cleared=updateCaptionEdit(beginCaptionEdit('saved'),'');assert.deepEqual(cancelCaptionEdit(),{editing:false,draft:''});const switched=updateCaptionEdit(beginCaptionEdit('other'),'unsaved');assert.deepEqual(cancelCaptionEdit(),{editing:false,draft:''});assert.equal(cleared.editing,true);assert.equal(switched.draft,'unsaved')});
test('pending and repeated caption saves block draft navigation until the active save settles',async()=>{assert.equal(canNavigateDuringCaptionSave(true),false);assert.equal(canNavigateDuringCaptionSave(false),true);const lock={current:false};let release!:()=>void,calls=0;const pending=new Promise<void>(resolve=>{release=resolve});const first=runExclusive(lock,async()=>{calls++;await pending});assert.equal(await runExclusive(lock,async()=>{calls++}),false);release();assert.equal(await first,true);assert.equal(calls,1)});
test('pending caption save disables textarea edits and keyboard exits',()=>{assert.equal(canInteractWithCaptionEdit(true),false);assert.equal(canInteractWithCaptionEdit(false),true)});
test('failed pending save retains the exact edit buffer after blocked Escape',()=>{const state=updateCaptionEdit(beginCaptionEdit('saved'),'exact unsaved edit');assert.equal(canInteractWithCaptionEdit(true),false);assert.deepEqual(completeCaptionEdit(false,state),state)});
test('legacy drafts receive stable identities and editorial dates without changing content',()=>{const slots=[{assetIds:['a'],kind:'Photo' as const,caption:'same caption',originalCaption:'same caption'}],first=restoreManualDrafts(slots,assets,'2026-10-04'),again=restoreManualDrafts(slots,assets,'2026-10-04');assert.equal(first.posts[0].id,again.posts[0].id);assert.equal(first.posts[0].planSlotId,again.posts[0].planSlotId);assert.equal(first.posts[0].planningDate,'2026-10-05');assert.equal(first.captions[first.posts[0].id],'same caption')});
test('suggested planning dates use Monday Wednesday Friday and are not publish schedules',()=>{assert.deepEqual(suggestedPlanningDates('2026-10-04'),['2026-10-05','2026-10-07','2026-10-09','2026-10-12','2026-10-14','2026-10-16'])});
test('approved coverage retains its position instead of reopening the slot',()=>{const draft=restoreManualDrafts([{draftId:'d2',planSlotId:'s2',planningDate:'2026-10-07',planPosition:1,assetIds:['a'],kind:'Photo',caption:'draft',originalCaption:'draft'}],assets,'2026-10-04').posts[0],cells=planCells([draft],[{slotId:'s1',position:0,planningDate:'2026-10-05',state:'approved',approvedPostId:'p1'}]);assert.equal(cells[0].type,'covered');assert.equal(cells[1].type,'draft');assert.equal(cells[2].type,'open')});
test('planning anchors use the America Chicago calendar across UTC boundaries',()=>{assert.equal(chicagoPlanningAnchor('2026-10-05T01:30:00.000Z'),'2026-10-04');assert.equal(chicagoPlanningAnchor('2026-03-08T08:30:00.000Z'),'2026-03-08')});
test('more than six drafts remain accessible in position order',()=>{const posts=Array.from({length:8},(_,index)=>({id:`d${index}`,draftId:`d${index}`,planSlotId:`s${index}`,planningDate:suggestedPlanningDates('2026-10-04',8)[index],planPosition:index,media:[assets[0]],kind:'Photo' as const}));const cells=planCells(posts,[]);assert.equal(cells.length,8);assert.deepEqual(cells.map(cell=>cell.type),Array(8).fill('draft'))});
test('rolling window excludes past coverage without hiding current or later drafts',()=>{const coverage=[{slotId:'old',position:0,planningDate:'2026-09-30',state:'approved' as const},{slotId:'current',position:1,planningDate:'2026-10-05',state:'approved' as const}],active=activePlanCoverage(coverage,'2026-10-04'),futureDraft:ManualPost={id:'d7',draftId:'d7',planSlotId:'s7',planningDate:'2026-10-19',planPosition:6,media:[assets[0]],kind:'Photo'},cells=planCells([futureDraft],active);assert.deepEqual(active.map(item=>item.slotId),['current']);assert.equal(cells.length,7);assert.equal(cells[0].type,'open');assert.equal(cells[1].type,'covered');assert.equal(cells[6].type,'draft')});
test('six approvals from last week allocate a new global position in the current week',()=>{const old=suggestedPlanningDates('2026-09-20').map((planningDate,position)=>({slotId:`old-${position}`,position,planningDate,state:'approved' as const}));assert.equal(nextPlanPosition([],old),6);assert.equal(nextPlanningDate([],old,'2026-10-04'),'2026-10-05')});
test('new-week drafts advance dates without reusing historical global positions',()=>{const old=suggestedPlanningDates('2026-09-20').map((planningDate,position)=>({slotId:`old-${position}`,position,planningDate,state:'approved' as const})),first:ManualPost={id:'new-6',planPosition:nextPlanPosition([],old),planningDate:nextPlanningDate([],old,'2026-10-04'),media:[assets[0]],kind:'Photo'},secondPosition=nextPlanPosition([first],old),secondDate=nextPlanningDate([first],old,'2026-10-04');assert.equal(first.planPosition,6);assert.equal(first.planningDate,'2026-10-05');assert.equal(secondPosition,7);assert.equal(secondDate,'2026-10-07')});
test('current board maps global overflow positions into current dated slots',()=>{const draft:ManualPost={id:'new-6',planPosition:6,planningDate:'2026-10-05',media:[assets[0]],kind:'Photo'},cells=planCells([draft],[],6,'2026-10-04');assert.equal(cells.length,6);assert.equal(cells[0].type,'draft');if(cells[0].type==='draft')assert.equal(cells[0].post.planPosition,6)});
test('one past draft remains visible once alongside six current drafts',()=>{const dates=suggestedPlanningDates('2026-10-04'),past:ManualPost={id:'past',planningDate:'2026-10-02',planPosition:0,media:[assets[0]],kind:'Photo'},current=dates.map((planningDate,index):ManualPost=>({id:`current-${index}`,planningDate,planPosition:index+1,media:[assets[0]],kind:'Photo'})),cells=planCells([past,...current],[],6,'2026-10-04'),drafts=cells.filter((cell):cell is Extract<typeof cell,{type:'draft'}>=>cell.type==='draft');assert.equal(drafts.length,7);assert.equal(drafts.filter(cell=>cell.post.id==='past').length,1);assert.equal(drafts.at(-1)?.backlog,true)});
test('all past drafts remain available as backlog without changing their dates',()=>{const posts=suggestedPlanningDates('2026-09-20').map((planningDate,index):ManualPost=>({id:`past-${index}`,planningDate,planPosition:index,media:[assets[0]],kind:'Photo'})),cells=planCells(posts,[],6,'2026-10-04'),backlog=cells.filter((cell):cell is Extract<typeof cell,{type:'draft'}>=>cell.type==='draft');assert.equal(cells.filter(cell=>cell.type==='open').length,6);assert.deepEqual(backlog.map(cell=>cell.post.planningDate),posts.map(post=>post.planningDate));assert.ok(backlog.every(cell=>cell.backlog))});
test('advancing the date moves a draft to backlog without editing or duplicating it',()=>{const draft:ManualPost={id:'rollover',planningDate:'2026-10-05',planPosition:12,media:[assets[0]],kind:'Reel'},before=planCells([draft],[],6,'2026-10-04'),after=planCells([draft],[],6,'2026-10-06'),beforeMatches=before.filter(cell=>cell.type==='draft'&&cell.post.id==='rollover'),afterMatches=after.filter(cell=>cell.type==='draft'&&cell.post.id==='rollover');assert.equal(beforeMatches.length,1);assert.equal(afterMatches.length,1);assert.equal(afterMatches[0].type==='draft'&&afterMatches[0].backlog,true);assert.equal(draft.planningDate,'2026-10-05');assert.equal(draft.planPosition,12)});
test('credited Photo and Reel captions preserve canonical user copy',()=>{assert.equal(composeApprovedCaption('Exact copy',['@photo']),'Exact copy\n\nPhoto: @photo');assert.equal(composeApprovedCaption('Exact reel copy',['@reel']),'Exact reel copy\n\nPhoto: @reel');assert.equal(composeApprovedCaption('Exact copy',[]),'Exact copy')});
test('approval request keeps credits separate from canonical queue caption',()=>{const post:ManualPost={id:'draft',draftId:'draft',planSlotId:'slot',planningDate:'2026-10-05',planPosition:6,media:[assets[0]],kind:'Photo'},payload=buildApprovalPayload(post,' Exact copy ',' Exact original ',['@credit','@credit'],'version-1');assert.equal(payload.caption,'Exact copy');assert.deepEqual(payload.photoCredits,['@credit']);assert.equal(composeApprovedCaption(payload.caption,payload.photoCredits),'Exact copy\n\nPhoto: @credit')});
test('approval replay replaces queue, coverage, and CAS token as one snapshot',()=>{const coverage=[{slotId:'approved-elsewhere',position:8,planningDate:'2026-10-09',state:'approved' as const,approvedPostId:'post-y'}],response={updatedAt:'version-3',coverage,slots:[{draftId:'other',planSlotId:'other-slot',planningDate:'2026-10-07',planPosition:7,assetIds:['b'],kind:'Reel' as const,caption:'Other-window caption',originalCaption:'Before'}]},reconciled=reconcileApprovalResponse(response,assets,'2026-10-04');assert.equal(reconciled?.updatedAt,'version-3');assert.deepEqual(reconciled?.posts.map(post=>post.id),['other']);assert.equal(reconciled?.captions.other,'Other-window caption');assert.deepEqual(reconciled?.coverage,coverage);assert.equal(nextPlanPosition(reconciled?.posts||[],reconciled?.coverage||[]),9);assert.equal(planCells(reconciled?.posts||[],reconciled?.coverage||[],6,'2026-10-04').filter(cell=>cell.type==='covered'&&cell.coverage.slotId==='approved-elsewhere').length,1)});
test('approval reconciliation rejects mixed snapshots that omit coverage',()=>{assert.equal(reconcileApprovalResponse({updatedAt:'version-3',slots:[]},assets,'2026-10-04'),null)});
test('approval route credit normalization rejects malformed values',()=>{assert.deepEqual(normalizePhotoCredits([' @one ','@one','@two']),['@one','@two']);assert.equal(normalizePhotoCredits(['bad\ncredit']),null);assert.equal(normalizePhotoCredits('not-an-array'),null)});
