import test from 'node:test';
import assert from 'node:assert/strict';
// Node 24 executes this TypeScript test directly; TypeScript's project config
// intentionally does not enable extension imports for application source.
// @ts-expect-error Node's direct TypeScript runner requires the explicit suffix.
import { activeManualMedia, appendManualDraft, approveOnce, beginCaptionEdit, cancelCaptionEdit, canApproveCaptionEdit, canInteractWithCaptionEdit, canNavigateDuringCaptionSave, completeCaptionEdit, reconcileRevision, requestRevision, restoreManualDrafts, runExclusive, serializeManualDrafts, tileMedia, updateCaptionEdit, type ManualAsset, type ManualPost } from './manual-content-drafts.ts';

const assets:ManualAsset[]=[{id:'a',storage_path:'a.jpg',file_type:'image/jpeg'},{id:'b',storage_path:'b.jpg',file_type:'image/jpeg'}];

test('restores exact captions and media order',()=>{const restored=restoreManualDrafts([{assetIds:['b','a'],kind:'Carousel',caption:' exact copy ',originalCaption:'original'}],assets);assert.deepEqual(restored.posts[0].media.map(a=>a.id),['b','a']);assert.equal(restored.captions[restored.posts[0].id],' exact copy ')});
test('preserves inaccessible media as ordered placeholders',()=>{const restored=restoreManualDrafts([{assetIds:['a','gone','b'],kind:'Carousel',caption:'keep me',originalCaption:'keep me'}],assets);assert.deepEqual(restored.posts[0].media.map(a=>a.id),['a','gone','b']);assert.equal(restored.posts[0].media[1].missing,true)});
test('appends without replacing existing drafts',()=>{const old:ManualPost={id:'old',media:[assets[0]],kind:'Photo'};const added:ManualPost={id:'new',media:[assets[1]],kind:'Photo'};const next=appendManualDraft({posts:[old],captions:{old:'old copy'},originals:{old:'old copy'}},added,'new copy');assert.deepEqual(next.posts.map(p=>p.id),['old','new']);assert.equal(next.captions.old,'old copy');assert.equal(next.captions.new,'new copy')});
test('duplicate save attempts are locked and failures release the lock',async()=>{const lock={current:false};let calls=0,release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve});const first=runExclusive(lock,async()=>{calls++;await pending});const duplicate=await runExclusive(lock,async()=>{calls++});assert.equal(duplicate,false);release();assert.equal(await first,true);await assert.rejects(()=>runExclusive(lock,async()=>{throw new Error('save failed')}));assert.equal(lock.current,false);await runExclusive(lock,async()=>{calls++});assert.equal(calls,2)});
test('failed approval can retry approval',async()=>{const succeeded=new Set<string>();let approvals=0;await assert.rejects(()=>approveOnce('p',succeeded,async()=>{approvals++;throw new Error('failed')},async()=>{}));await approveOnce('p',succeeded,async()=>{approvals++},async()=>{});assert.equal(approvals,2)});
test('successful approval is not repeated when cleanup retries',async()=>{const succeeded=new Set<string>();let approvals=0,cleanups=0;await assert.rejects(()=>approveOnce('p',succeeded,async()=>{approvals++},async()=>{cleanups++;throw new Error('queue failed')}));await approveOnce('p',succeeded,async()=>{approvals++},async()=>{cleanups++});assert.equal(approvals,1);assert.equal(cleanups,2)});
test('serializes the compatible slot shape with ordered media and caption edits',()=>{const post:ManualPost={id:'p',media:[assets[1],assets[0]],kind:'Carousel',purpose:'Wedding'};assert.deepEqual(serializeManualDrafts([post],{p:'edited'},{p:'original'}),[{assetIds:['b','a'],kind:'Carousel',caption:'edited',originalCaption:'original',purpose:'Wedding'}])});
test('tile uses first ordered asset and missing media remains visible',()=>{const restored=restoreManualDrafts([{assetIds:['gone','a'],kind:'Carousel',caption:'copy',originalCaption:'copy'}],assets);assert.equal(tileMedia(restored.posts[0])?.id,'gone');assert.equal(tileMedia(restored.posts[0])?.missing,true)});
test('stale carousel slide safely falls back across photo, reel, missing media, and another carousel',()=>{const reel:ManualAsset={id:'reel',storage_path:'reel.mp4',file_type:'video/mp4'},missing:ManualAsset={id:'gone',storage_path:'',file_type:'application/x-missing',missing:true};const posts:ManualPost[]=[{id:'photo',media:[assets[0]],kind:'Photo'},{id:'reel',media:[reel],kind:'Reel'},{id:'missing',media:[missing],kind:'Photo'},{id:'carousel',media:[assets[1],assets[0]],kind:'Carousel'}];assert.equal(activeManualMedia(posts[0],1)?.id,'a');assert.equal(activeManualMedia(posts[1],1)?.id,'reel');assert.equal(activeManualMedia(posts[2],1)?.missing,true);assert.equal(activeManualMedia(posts[3],1)?.id,'a')});
test('legacy queue slots restore without revision state',()=>{const restored=restoreManualDrafts([{assetIds:['a'],kind:'Photo',caption:'legacy',originalCaption:'legacy'}],assets);assert.equal(restored.posts[0].revision,undefined)});
test('revision notes and waiting status survive serialization and refresh',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},' More personality, please. ','caption','2026-10-04T15:22:00.000Z'),slot=serializeManualDrafts([post],{p:'caption'},{p:'caption'})[0],restored=restoreManualDrafts([slot],assets);assert.equal(restored.posts[0].revision?.note,'More personality, please.');assert.equal(restored.posts[0].revision?.status,'waiting')});
test('unchanged and interrupted caption edits remain waiting',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},'warmer','same','2026-10-04T15:22:00.000Z');assert.equal(reconcileRevision(post,'same','later').revision?.status,'waiting');assert.equal(post.revision?.status,'waiting')});
test('persisted caption change distinguishes a completed revision',()=>{const post=requestRevision({id:'p',media:[assets[0]],kind:'Photo'},'warmer','before','2026-10-04T15:22:00.000Z'),revised=reconcileRevision(post,'after','2026-10-04T16:00:00.000Z');assert.equal(revised.revision?.status,'revised');assert.equal(revised.revision?.note,'warmer');assert.equal(revised.revision?.revisedAt,'2026-10-04T16:00:00.000Z')});
test('caption editor exits and clears its buffer only after successful persistence',()=>{const editing=updateCaptionEdit(beginCaptionEdit('saved'),'changed');assert.deepEqual(completeCaptionEdit(true,editing),{editing:false,draft:''})});
test('caption editor preserves its buffer when persistence fails',()=>{const editing=updateCaptionEdit(beginCaptionEdit('saved'),'changed');assert.deepEqual(completeCaptionEdit(false,editing),editing)});
test('caption editing gates approval until Save or Cancel resolves it',()=>{const editing=beginCaptionEdit('saved');assert.equal(canApproveCaptionEdit(editing),false);assert.equal(canApproveCaptionEdit(completeCaptionEdit(true,editing)),true);assert.equal(canApproveCaptionEdit(cancelCaptionEdit()),true)});
test('clear then Cancel and switch then Cancel discard only the edit buffer',()=>{const cleared=updateCaptionEdit(beginCaptionEdit('saved'),'');assert.deepEqual(cancelCaptionEdit(),{editing:false,draft:''});const switched=updateCaptionEdit(beginCaptionEdit('other'),'unsaved');assert.deepEqual(cancelCaptionEdit(),{editing:false,draft:''});assert.equal(cleared.editing,true);assert.equal(switched.draft,'unsaved')});
test('pending and repeated caption saves block draft navigation until the active save settles',async()=>{assert.equal(canNavigateDuringCaptionSave(true),false);assert.equal(canNavigateDuringCaptionSave(false),true);const lock={current:false};let release!:()=>void,calls=0;const pending=new Promise<void>(resolve=>{release=resolve});const first=runExclusive(lock,async()=>{calls++;await pending});assert.equal(await runExclusive(lock,async()=>{calls++}),false);release();assert.equal(await first,true);assert.equal(calls,1)});
test('pending caption save disables textarea edits and keyboard exits',()=>{assert.equal(canInteractWithCaptionEdit(true),false);assert.equal(canInteractWithCaptionEdit(false),true)});
test('failed pending save retains the exact edit buffer after blocked Escape',()=>{const state=updateCaptionEdit(beginCaptionEdit('saved'),'exact unsaved edit');assert.equal(canInteractWithCaptionEdit(true),false);assert.deepEqual(completeCaptionEdit(false,state),state)});
