export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type MediaDecision = 'pending' | 'strong' | 'edit' | 'skip'

export type Database = { public: { Tables: {
 profiles:{Row:{id:string;email:string;full_name:string|null;business_name:string|null;created_at:string;updated_at:string};Insert:{id:string;email:string;full_name?:string|null;business_name?:string|null;created_at?:string;updated_at?:string};Update:{full_name?:string|null;business_name?:string|null;updated_at?:string}}
 posts:{Row:{id:string;user_id:string;title:string;pillar:string;topic:string|null;format:'Reel'|'Carousel'|'Photo';caption_option1:string|null;caption_option2:string|null;caption_option3:string|null;hashtags:string[];shot_ideas:string[];status:'draft'|'scheduled'|'published';scheduled_date:string|null;notes:string|null;thumbnail_url:string|null;approved:boolean;created_at:string;updated_at:string};Insert:{id?:string;user_id:string;title:string;pillar:string;topic?:string|null;format:'Reel'|'Carousel'|'Photo';caption_option1?:string|null;caption_option2?:string|null;caption_option3?:string|null;hashtags?:string[];shot_ideas?:string[];status?:'draft'|'scheduled'|'published';scheduled_date?:string|null;notes?:string|null;thumbnail_url?:string|null;approved?:boolean;created_at?:string;updated_at?:string};Update:{title?:string;pillar?:string;topic?:string|null;format?:'Reel'|'Carousel'|'Photo';caption_option1?:string|null;caption_option2?:string|null;caption_option3?:string|null;hashtags?:string[];shot_ideas?:string[];status?:'draft'|'scheduled'|'published';scheduled_date?:string|null;notes?:string|null;thumbnail_url?:string|null;approved?:boolean;updated_at?:string}}
 media_assets:{Row:{id:string;user_id:string;filename:string;storage_path:string;file_type:string;size_bytes:number;tags:string[];notes:string|null;created_at:string;folder_id:string|null;photographer:string|null;ai_status:MediaDecision;ai_score:number|null;ai_reason:string|null;ai_categories:string[];ai_uses:string[];ai_edit_suggestion:string|null;ai_analyzed_at:string|null;ai_duplicate_of:string|null;ai_override_status:MediaDecision|null;ai_override_reason:string|null;used_in_content:boolean};Insert:{id?:string;user_id:string;filename:string;storage_path:string;file_type:string;size_bytes:number;tags?:string[];notes?:string|null;created_at?:string;folder_id?:string|null;photographer?:string|null;ai_status?:MediaDecision;ai_score?:number|null;ai_reason?:string|null;ai_categories?:string[];ai_uses?:string[];ai_edit_suggestion?:string|null;ai_analyzed_at?:string|null;ai_duplicate_of?:string|null;ai_override_status?:MediaDecision|null;ai_override_reason?:string|null;used_in_content?:boolean};Update:{filename?:string;tags?:string[];notes?:string|null;folder_id?:string|null;photographer?:string|null;ai_status?:MediaDecision;ai_score?:number|null;ai_reason?:string|null;ai_categories?:string[];ai_uses?:string[];ai_edit_suggestion?:string|null;ai_analyzed_at?:string|null;ai_duplicate_of?:string|null;ai_override_status?:MediaDecision|null;ai_override_reason?:string|null;used_in_content?:boolean}}
 post_media:{Row:{id:string;post_id:string;asset_id:string;display_order:number;created_at:string};Insert:{id?:string;post_id:string;asset_id:string;display_order?:number;created_at?:string};Update:{display_order?:number}}
 user_settings:{Row:{id:string;user_id:string;key:string;value:Json;updated_at:string};Insert:{id?:string;user_id:string;key:string;value:Json;updated_at?:string};Update:{value?:Json;updated_at?:string}}
 caption_templates:{Row:{id:string;user_id:string;name:string;pillar:string;option1:string|null;option2:string|null;hashtags:string[];notes:string|null;created_at:string;updated_at:string};Insert:{id?:string;user_id:string;name:string;pillar:string;option1?:string|null;option2?:string|null;hashtags?:string[];notes?:string|null;created_at?:string;updated_at?:string};Update:{name?:string;pillar?:string;option1?:string|null;option2?:string|null;hashtags?:string[];notes?:string|null;updated_at?:string}}
 media_feedback:{Row:{id:string;user_id:string;asset_id:string|null;original_status:MediaDecision|null;corrected_status:MediaDecision;reason:string;created_at:string};Insert:{id?:string;user_id:string;asset_id?:string|null;original_status?:MediaDecision|null;corrected_status:MediaDecision;reason:string;created_at?:string};Update:{corrected_status?:MediaDecision;reason?:string}}
};Views:Record<string,never>;Functions:Record<string,never>;Enums:Record<string,never>;CompositeTypes:Record<string,never>}}

export type Profile=Database['public']['Tables']['profiles']['Row']
export type Post=Database['public']['Tables']['posts']['Row']
export type MediaAsset=Database['public']['Tables']['media_assets']['Row']
export type CaptionTemplate=Database['public']['Tables']['caption_templates']['Row']
export type MediaFeedback=Database['public']['Tables']['media_feedback']['Row']
export type PostInsert=Database['public']['Tables']['posts']['Insert']
export type PostUpdate=Database['public']['Tables']['posts']['Update']
export type CaptionTemplateInsert=Database['public']['Tables']['caption_templates']['Insert']
