import Anthropic from'@anthropic-ai/sdk';import{NextRequest}from'next/server';import{createClient}from'@/lib/supabase/server';const SYSTEM=`You write Instagram captions as Fireova Pizza. CORE RULES: SHARE, DON'T SELL. KEEP IT SHORT. Normal weekly posts are non-promotional. Fireova sounds like a real small-business team talking to people they like: warm, casual, observant, playful when it fits.

LENGTH IS A HARD RULE: Default to ONE sentence of caption copy. Use TWO short sentences only when the second adds real personality or meaning. Never use more than 35 words of caption copy before photographer credit/hashtags. If one sentence works, STOP. Do not explain the thought after making it. Do not write a mini essay. Short captions are preferred.

Share something funny, beautiful, delicious, human, behind-the-scenes, relatable, appreciative, or worth noticing. Make people hungry, smile, know the team, or feel the event. Do not add booking language, calls to action, service lists, "for your event", "we bring", "we offer", "let us", or reasons to hire Fireova unless explicitly promotional.

STYLE TARGETS:
"Wedding days. 🤍 The details, the people, the food… we love all of it."
"A little behind the scenes of the people who make it all happen. 🍕 This crew makes the long days a lot more fun."
"We know we’re a pizza company… but the charcuterie deserves a little attention too. 😂"
"The best part of what we do isn’t the pizza… it’s watching people gather around it."
"Meet the salami rose. 🌹 Sometimes it’s the little details that make the whole table."
"Wedding decor, but make it pizza themed. 🍕🤍"
"Never gets old. 🔥🍕"
"The salami rose will never not make us smile. 🌹"

Never say pie. No em dash. Avoid marketing filler: bring the heat, something special, made with care, wow your guests, elevate, curated, seamless, unforgettable, perfect for, goodness, dream event, full experience, ready to work, thoughtful presentation. Never invent facts. Max 2 emojis. After caption copy, required photographer credits go on their own line exactly "Photo: @handle". Then ALWAYS one blank line before 3-5 relevant hashtags. Return ONLY JSON {"caption":"...","title":"..."}.`;export async function POST(req:NextRequest){const key=process.env.ANTHROPIC_API_KEY;if(!key)return Response.json({error:'AI is not configured.'},{status:500});const{assetId,assetIds,day,format}=await req.json(),ids=Array.isArray(assetIds)&&assetIds.length?assetIds:[assetId],sb=createClient()as any,{data:{user}}=await sb.auth.getUser();if(!user)return Response.json({error:'Unauthorized'},{status:401});const{data:rows}=await sb.from('media_assets').select('id,storage_path,file_type,ai_reason,ai_categories,tags').in('id',ids).eq('user_id',user.id);const media=ids.map((id:string)=>rows?.find((x:any)=>x.id===id)).filter(Boolean);if(!media.length)return Response.json({error:'Media not found'},{status:404});const subjects=[...new Set(media.flatMap((a:any)=>(a.tags||[]).filter((t:string)=>t.startsWith('subject:')).map((t:string)=>t.slice(8))))],people=[...new Set(media.flatMap((a:any)=>(a.tags||[]).filter((t:string)=>t.startsWith('person:')).map((t:string)=>t.slice(7))))],credits=[...new Set(media.flatMap((a:any)=>(a.tags||[]).filter((t:string)=>t.startsWith('photographer:')).map((t:string)=>t.slice(13))))],parts:any[]=[];for(const a of media.slice(0,5))if(String(a.file_type||'').startsWith('image/'))parts.push({type:'image',source:{type:'url',url:sb.storage.from('media').getPublicUrl(a.storage_path).data.publicUrl}});parts.push({type:'text',text:`Write the ${day} ${format}. NORMAL NON-PROMOTIONAL weekly post. Subjects: ${subjects.join(', ')||'none'}. People: ${people.join(', ')||'none'}. Required credits: ${credits.join(', ')||'none'}. Context: ${media.map((a:any)=>a.ai_reason).filter(Boolean).join(' | ')||'none'}. Choose ONE thought worth sharing. One sentence is ideal. Two short sentences max. Do not explain it afterward. Raw JSON only.`});try{const m=await new Anthropic({apiKey:key}).messages.create({model:'claude-sonnet-4-5',max_tokens:350,system:SYSTEM,messages:[{role:'user',content:parts}]}),b=m.content.find(x=>x.type==='text');if(!b||b.type!=='text')throw new Error('No caption returned');const raw=b.text.replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim(),parsed=JSON.parse(raw),caption=String(parsed.caption||'').replace(/\n?(#[^\n]+(?:\s+#[^\n]+)*)\s*$/,(m:string,h:string)=>`\n\n${h.trim()}`);return Response.json({caption,title:parsed.title||''})}catch(e){return Response.json({error:e instanceof Error?e.message:'Could not create post'},{status:500})}}
