'use client'

import { useEffect,useMemo,useRef,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Asset={id:string;filename:string;storage_path:string;file_type:string;ai_status?:string|null;user_override_status?:string|null}
type Guide={summary?:string;steps?:{title?:string;path?:string;settings?:string[];why?:string}[];stop?:string}
export default function PhotoPolishActions({assets}:{assets:Asset[]}){
 const[selectedId,setSelectedId]=useState(assets[0]?.id??''),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[guide,setGuide]=useState<Guide|null>(null),[guideError,setGuideError]=useState<string|null>(null),[guideBusy,setGuideBusy]=useState(false);const inputRef=useRef<HTMLInputElement|null>(null),sb=createClient();const selected=useMemo(()=>assets.find(a=>a.id===selectedId)??assets[0],[assets,selectedId]),status=String(selected?.user_override_status||selected?.ai_status||'').toLowerCase(),photo=selected&&selected.file_type?.startsWith('image/')&&(status==='strong'||status==='edit')
 useEffect(()=>{const handler=(event:MouseEvent)=>{const button=(event.target as HTMLElement)?.closest('button');if(!button)return;const name=button.querySelector('p.font-semibold')?.textContent?.trim();if(!name)return;const match=assets.find(a=>a.filename===name);if(match){setSelectedId(match.id);setMessage(null)}};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[assets])
 useEffect(()=>{if(!photo||!selected)return;let cancelled=false;setGuide(null);setGuideError(null);setGuideBusy(true);fetch(`/api/media-assets/${encodeURIComponent(selected.id)}/lightroom-guide`,{method:'POST'}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not analyze photo.');if(!cancelled)setGuide(d)}).catch(e=>{if(!cancelled)setGuideError(e instanceof Error?e.message:'Could not analyze photo.')}).finally(()=>{if(!cancelled)setGuideBusy(false)});return()=>{cancelled=true}},[selected?.id,photo])
 async function downloadOriginal(){if(!selected)return;setBusy(true);setMessage(null);try{const u=sb.storage.from('media').getPublicUrl(selected.storage_path).data.publicUrl,r=await fetch(u);if(!r.ok)throw new Error('Could not download the original photo.');const blob=await r.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=selected.filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(href)}catch(e){setMessage(e instanceof Error?e.message:'Could not download the photo.')}finally{setBusy(false)}}
 async function uploadEdited(file:File){if(!selected)return;setBusy(true);setMessage('Uploading Lightroom edit…');try{const form=new FormData();form.append('file',file);const r=await fetch(`/api/media-assets/${encodeURIComponent(selected.id)}/lightroom-replace`,{method:'POST',body:form}),raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||`Upload failed (${r.status})`);setMessage('Edited photo uploaded. Re-reviewing with AI…');const review=await fetch('/api/analyze-media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetId:d.edited.id})});if(!review.ok)throw new Error('Edited photo saved, but AI re-review failed.');setMessage('Done. Refreshing…');setTimeout(()=>location.reload(),700)}catch(e){setMessage(e instanceof Error?e.message:'Could not upload the edited photo.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 if(!photo)return null
 return <div className="fixed bottom-5 right-5 z-40 max-h-[75vh] w-[min(460px,calc(100vw-40px))] overflow-y-auto rounded-xl border bg-white p-4 shadow-xl"><p className="text-[10px] font-semibold uppercase tracking-wider text-stone-400">Edit this photo in Lightroom</p><p className="mt-1 truncate text-sm font-semibold">{selected.filename}</p>{guideBusy&&<p className="mt-3 text-xs text-stone-500">Looking at this photo and building Lightroom steps…</p>}{guideError&&<p className="mt-3 text-xs text-red-600">{guideError}</p>}{guide&&<div className="mt-3"><p className="text-xs leading-5 text-stone-600">{guide.summary}</p><div className="mt-3 space-y-3">{(guide.steps||[]).map((s,i)=><div key={i} className="rounded-lg bg-stone-50 p-3"><p className="text-xs font-semibold text-stone-800">{i+1}. {s.title}</p>{s.path&&<p className="mt-1 text-[11px] font-medium text-orange-700">{s.path}</p>}{s.settings?.map((x,j)=><p key={j} className="mt-1 text-xs text-stone-700">{x}</p>)}{s.why&&<p className="mt-1 text-[11px] leading-4 text-stone-500">Why: {s.why}</p>}</div>)}</div>{guide.stop&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-emerald-700">Stop</p><p className="mt-1 text-xs leading-5 text-emerald-800">{guide.stop}</p></div>}</div>}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={downloadOriginal} disabled={busy} className="btn-secondary justify-center disabled:opacity-50">Download Original</button><button onClick={()=>inputRef.current?.click()} disabled={busy} className="btn-primary justify-center disabled:opacity-50">Replace With Edited</button></div><input ref={inputRef} type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.heic,.heif" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadEdited(f)}}/>{message&&<p className="mt-3 text-xs text-stone-600">{message}</p>}<p className="mt-3 text-[11px] leading-4 text-stone-400">Starting values are photo-specific suggestions. Make the smallest change that works and stop before the image looks processed.</p></div>
}
