'use client'

import { useEffect,useMemo,useRef,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Asset={id:string;filename:string;storage_path:string;file_type:string;ai_status?:string|null;user_override_status?:string|null}
type Guide={summary?:string;steps?:{title?:string;path?:string;settings?:string[];why?:string}[];stop?:string}
export default function PhotoPolishActions({assets}:{assets:Asset[]}){
 const[selectedId,setSelectedId]=useState(assets[0]?.id??''),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[guide,setGuide]=useState<Guide|null>(null),[guideError,setGuideError]=useState<string|null>(null),[guideBusy,setGuideBusy]=useState(false),[open,setOpen]=useState(false);const inputRef=useRef<HTMLInputElement|null>(null),sb=createClient();const selected=useMemo(()=>assets.find(a=>a.id===selectedId)??assets[0],[assets,selectedId]),status=String(selected?.user_override_status||selected?.ai_status||'').toLowerCase(),photo=selected&&selected.file_type?.startsWith('image/')&&(status==='strong'||status==='edit')
 useEffect(()=>{const handler=(event:MouseEvent)=>{const button=(event.target as HTMLElement)?.closest('button');if(!button)return;const name=button.querySelector('p.font-semibold')?.textContent?.trim();if(!name)return;const match=assets.find(a=>a.filename===name);if(match){setSelectedId(match.id);setMessage(null);setGuide(null);setGuideError(null);setOpen(false)}};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true)},[assets])
 async function getGuide(){if(!selected)return;setOpen(true);if(guide||guideBusy)return;setGuideError(null);setGuideBusy(true);try{const r=await fetch(`/api/media-assets/${encodeURIComponent(selected.id)}/lightroom-guide`,{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not analyze photo.');setGuide(d)}catch(e){setGuideError(e instanceof Error?e.message:'Could not analyze photo.')}finally{setGuideBusy(false)}}
 async function downloadOriginal(){if(!selected)return;setBusy(true);setMessage(null);try{const u=sb.storage.from('media').getPublicUrl(selected.storage_path).data.publicUrl,r=await fetch(u);if(!r.ok)throw new Error('Could not download the original photo.');const blob=await r.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=selected.filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(href)}catch(e){setMessage(e instanceof Error?e.message:'Could not download the photo.')}finally{setBusy(false)}}
 async function uploadEdited(file:File){if(!selected)return;setBusy(true);setMessage('Uploading Lightroom edit…');try{const form=new FormData();form.append('file',file);const r=await fetch(`/api/media-assets/${encodeURIComponent(selected.id)}/lightroom-replace`,{method:'POST',body:form}),raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||`Upload failed (${r.status})`);setMessage('Edited photo uploaded. Re-reviewing with AI…');const review=await fetch('/api/analyze-media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assetId:d.edited.id})});if(!review.ok)throw new Error('Edited photo saved, but AI re-review failed.');setMessage('Done. Refreshing…');setTimeout(()=>location.reload(),700)}catch(e){setMessage(e instanceof Error?e.message:'Could not upload the edited photo.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 if(!photo)return null
 return <><div className="fixed bottom-5 right-5 z-40 flex gap-2 rounded-xl border bg-white p-2 shadow-lg"><button onClick={()=>void getGuide()} className="btn-secondary justify-center">Lightroom Instructions</button><button onClick={()=>inputRef.current?.click()} disabled={busy} className="btn-primary justify-center disabled:opacity-50">Replace Photo</button><input ref={inputRef} type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.heic,.heif" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadEdited(f)}}/></div>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setOpen(false)}><div className="max-h-[85vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-stone-400">Edit this photo in Lightroom</p><p className="mt-1 text-base font-semibold">{selected.filename}</p></div><button onClick={()=>setOpen(false)} className="text-2xl leading-none text-stone-400">×</button></div>{guideBusy&&<p className="mt-5 text-sm text-stone-500">Analyzing this exact photo for the smallest natural Lightroom edit…</p>}{guideError&&<p className="mt-5 text-sm text-red-600">{guideError}</p>}{guide&&<div className="mt-4"><p className="text-sm leading-6 text-stone-600">{guide.summary}</p><div className="mt-4 space-y-3">{(guide.steps||[]).map((s,i)=><div key={i} className="rounded-xl bg-stone-50 p-4"><p className="text-sm font-semibold text-stone-900">{i+1}. {s.title}</p>{s.path&&<p className="mt-1 text-xs font-medium text-orange-700">{s.path}</p>}{s.settings?.map((x,j)=><p key={j} className="mt-1 text-sm text-stone-700">{x}</p>)}{s.why&&<p className="mt-2 text-xs leading-5 text-stone-500">Why: {s.why}</p>}</div>)}</div>{guide.stop&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Stop here</p><p className="mt-1 text-sm leading-6 text-emerald-800">{guide.stop}</p></div>}<div className="mt-4 grid grid-cols-2 gap-2"><button onClick={downloadOriginal} disabled={busy} className="btn-secondary justify-center">Download Original</button><button onClick={()=>inputRef.current?.click()} disabled={busy} className="btn-primary justify-center">Replace Photo</button></div></div>}{message&&<p className="mt-3 text-xs text-stone-600">{message}</p>}</div></div>}</>
}
