import Anthropic from '@anthropic-ai/sdk'
import {NextRequest}from'next/server'
import{createClient}from'@/lib/supabase/server'
const SYSTEM=`You review short-form video for Fireova, a DFW event catering company known for its mobile wood-fired pizza experience. Fireova is more than pizza: grazing/charcuterie, small bites, salads, sides, desserts, team/service, guests, venues, decor, behind-the-scenes and event experience are all valid content.
You receive several frames sampled across ONE video. Judge the VIDEO as a whole from those frames.

DECISION STANDARD:
STRONG: useful visual story/action, flattering people or food, and good enough to publish with only routine platform trimming.
EDIT: the underlying footage is genuinely post-worthy and can realistically be made publishable with NORMAL edits available to a business owner: choose the clearest section, trim beginning/end, stabilize if feasible, crop/reframe, modest exposure/white-balance/color correction. Use Edit only when those ordinary changes are likely to solve the problem.
SKIP: normal editing cannot realistically make the footage post-worthy. Examples: severe or persistent motion blur, major focus failure, unusable camera movement, important subject repeatedly obscured, strongly unflattering people/food, or footage with no useful visual moment. If your reason says the problem 'severely degrades' the footage, needs a reshoot, or cannot be fixed with ordinary editing, choose SKIP rather than Edit.

EDIT ADVICE MUST BE USER-FACING. Never mention sampled frame numbers, AI frames, frame 1/2/3, or internal analysis mechanics. Say things like 'Use the clearest portion of the clip, trim the shaky opening, stabilize if possible, tighten the crop around the pizza, and correct the warm cast.' Do not recommend impossible recovery such as sharpening badly blurred footage into clarity.
Do not reject footage because it is not pizza. Do not invent audio or action not visible in the sampled frames.
Return ONLY raw JSON: {"status":"strong|edit|skip","score":0,"reason":"specific reason","categories":["..."],"uses":["..."],"edit_suggestion":"plain-language actionable edit or null"}`
export async function POST(req:NextRequest){try{const sb=createClient(),{data:{user}}=await sb.auth.getUser();if(!user)return Response.json({error:'Unauthorized'},{status:401});const key=process.env.ANTHROPIC_API_KEY;if(!key)return Response.json({error:'AI is not configured'},{status:500});const body=await req.json()as{assetId?:string;frames?:string[]};if(!body.assetId||!body.frames?.length)return Response.json({error:'assetId and video frames are required'},{status:400});const{data:a,error}=await sb.from('media_assets').select('*').eq('id',body.assetId).eq('user_id',user.id).single();if(error||!a)return Response.json({error:'Video not found'},{status:404});if(!a.file_type?.startsWith('video/'))return Response.json({error:'This asset is not a video'},{status:400});const frames=body.frames.slice(0,6),content:any[]=frames.map(f=>({type:'image',source:{type:'base64',media_type:'image/jpeg',data:f.replace(/^data:image\/jpeg;base64,/,'')}}));content.push({type:'text',text:`These images are evenly sampled across the short video ${a.filename}. Judge whether the footage is truly usable for Fireova social media. Apply the Strong/Edit/Skip standard strictly. Return only raw JSON.`});const client=new Anthropic({apiKey:key});let msg;try{msg=await client.messages.create({model:'claude-sonnet-4-5',max_tokens:700,system:SYSTEM,messages:[{role:'user',content}]})}catch(e:unknown){return Response.json({error:`Anthropic: ${e instanceof Error?e.message:'API error'}`},{status:502})}const b=msg.content.find(x=>x.type==='text'),raw=b&&b.type==='text'?b.text.trim():'';let p:any;try{p=JSON.parse(raw.replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim())}catch{return Response.json({error:`Invalid AI response: ${raw.slice(0,160)}`},{status:502})}const status=['strong','edit','skip'].includes(p.status)?p.status:'skip',patch={ai_status:status,ai_quality_score:Math.max(0,Math.min(100,Number(p.score)||0)),ai_reason:String(p.reason||''),ai_categories:Array.isArray(p.categories)?p.categories.slice(0,8):[],ai_post_uses:Array.isArray(p.uses)?p.uses.slice(0,6):[],ai_edit_suggestion:p.edit_suggestion?String(p.edit_suggestion):null,ai_reviewed_at:new Date().toISOString()};const{error:save}=await sb.from('media_assets').update(patch).eq('id',a.id).eq('user_id',user.id);if(save)return Response.json({error:`Supabase save failed: ${save.message}`},{status:500});return Response.json({id:a.id,...patch})}catch(e:unknown){return Response.json({error:`Server: ${e instanceof Error?e.message:'Unknown error'}`},{status:500})}}
