import Anthropic from '@anthropic-ai/sdk'
import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const SYSTEM=`You review short-form video for Fireova, a DFW event catering company known for its mobile wood-fired pizza experience. Fireova is more than pizza: grazing/charcuterie, small bites, salads, sides, desserts, team/service, guests, venues, decor, behind-the-scenes and event experience are all valid content.
You will receive several frames sampled across ONE video. Judge the VIDEO as a whole from these frames.
Strong = useful visual story/action, flattering people/food, good enough to use as Reel/B-roll/Story. Edit = useful footage that needs normal color/exposure/crop/trimming. Skip = genuinely poor/unusable, severe blur/obstruction, unflattering moment, bad food presentation, or no useful visual content.
Do not reject footage because it is not pizza. Do not invent audio or action not visible in frames.
Return ONLY raw JSON: {"status":"strong|edit|skip","score":0,"reason":"specific reason","categories":["..."],"uses":["..."],"edit_suggestion":"specific edit or null"}`

export async function POST(req:NextRequest){try{const sb=createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return Response.json({error:'Unauthorized'},{status:401});const key=process.env.ANTHROPIC_API_KEY;if(!key)return Response.json({error:'AI is not configured'},{status:500});const body=await req.json() as {assetId?:string;frames?:string[]};if(!body.assetId||!body.frames?.length)return Response.json({error:'assetId and video frames are required'},{status:400});const{data:a,error}=await sb.from('media_assets').select('*').eq('id',body.assetId).eq('user_id',user.id).single();if(error||!a)return Response.json({error:'Video not found'},{status:404});if(!a.file_type?.startsWith('video/'))return Response.json({error:'This asset is not a video'},{status:400});const frames=body.frames.slice(0,6);const content:any[]=frames.map(f=>({type:'image',source:{type:'base64',media_type:'image/jpeg',data:f.replace(/^data:image\/jpeg;base64,/,'')}}));content.push({type:'text',text:`These ${frames.length} frames are sampled across the video ${a.filename}. Review the full clip for Fireova social content. Return only raw JSON.`});const client=new Anthropic({apiKey:key});let msg;try{msg=await client.messages.create({model:'claude-sonnet-4-5',max_tokens:700,system:SYSTEM,messages:[{role:'user',content}]})}catch(e:unknown){return Response.json({error:`Anthropic: ${e instanceof Error?e.message:'API error'}`},{status:502})}const b=msg.content.find(x=>x.type==='text'),raw=b&&b.type==='text'?b.text.trim():'';let p:any;try{p=JSON.parse(raw.replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim())}catch{return Response.json({error:`Invalid AI response: ${raw.slice(0,160)}`},{status:502})}const status=['strong','edit','skip'].includes(p.status)?p.status:'skip';const patch={ai_status:status,ai_quality_score:Math.max(0,Math.min(100,Number(p.score)||0)),ai_reason:String(p.reason||''),ai_categories:Array.isArray(p.categories)?p.categories.slice(0,8):[],ai_post_uses:Array.isArray(p.uses)?p.uses.slice(0,6):[],ai_edit_suggestion:p.edit_suggestion?String(p.edit_suggestion):null,ai_reviewed_at:new Date().toISOString()};const{error:save}=await sb.from('media_assets').update(patch).eq('id',a.id).eq('user_id',user.id);if(save)return Response.json({error:`Supabase save failed: ${save.message}`},{status:500});return Response.json({id:a.id,...patch})}catch(e:unknown){return Response.json({error:`Server: ${e instanceof Error?e.message:'Unknown error'}`},{status:500})}}
